// Code generated by go-swagger; DO NOT EDIT.

package testflow

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/hunjixin/brightbird/models"
)

// NewChangetestflowParams creates a new ChangetestflowParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewChangetestflowParams() *ChangetestflowParams {
	return &ChangetestflowParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewChangetestflowParamsWithTimeout creates a new ChangetestflowParams object
// with the ability to set a timeout on a request.
func NewChangetestflowParamsWithTimeout(timeout time.Duration) *ChangetestflowParams {
	return &ChangetestflowParams{
		timeout: timeout,
	}
}

// NewChangetestflowParamsWithContext creates a new ChangetestflowParams object
// with the ability to set a context for a request.
func NewChangetestflowParamsWithContext(ctx context.Context) *ChangetestflowParams {
	return &ChangetestflowParams{
		Context: ctx,
	}
}

// NewChangetestflowParamsWithHTTPClient creates a new ChangetestflowParams object
// with the ability to set a custom HTTPClient for a request.
func NewChangetestflowParamsWithHTTPClient(client *http.Client) *ChangetestflowParams {
	return &ChangetestflowParams{
		HTTPClient: client,
	}
}

/*
ChangetestflowParams contains all the parameters to send to the API endpoint

	for the changetestflow operation.

	Typically these are written to a http.Request.
*/
type ChangetestflowParams struct {

	/* ChangGroupRequest.

	   params with group id and testflows
	*/
	ChangGroupRequest *models.ChangeTestflowGroupRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the changetestflow params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ChangetestflowParams) WithDefaults() *ChangetestflowParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the changetestflow params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ChangetestflowParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the changetestflow params
func (o *ChangetestflowParams) WithTimeout(timeout time.Duration) *ChangetestflowParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the changetestflow params
func (o *ChangetestflowParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the changetestflow params
func (o *ChangetestflowParams) WithContext(ctx context.Context) *ChangetestflowParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the changetestflow params
func (o *ChangetestflowParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the changetestflow params
func (o *ChangetestflowParams) WithHTTPClient(client *http.Client) *ChangetestflowParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the changetestflow params
func (o *ChangetestflowParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithChangGroupRequest adds the changGroupRequest to the changetestflow params
func (o *ChangetestflowParams) WithChangGroupRequest(changGroupRequest *models.ChangeTestflowGroupRequest) *ChangetestflowParams {
	o.SetChangGroupRequest(changGroupRequest)
	return o
}

// SetChangGroupRequest adds the changGroupRequest to the changetestflow params
func (o *ChangetestflowParams) SetChangGroupRequest(changGroupRequest *models.ChangeTestflowGroupRequest) {
	o.ChangGroupRequest = changGroupRequest
}

// WriteToRequest writes these params to a swagger request
func (o *ChangetestflowParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.ChangGroupRequest != nil {
		if err := r.SetBodyParam(o.ChangGroupRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
