// Code generated by go-swagger; DO NOT EDIT.

package testflow

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ipfs-force-community/brightbird/models"
)

// NewCopyTestflowParams creates a new CopyTestflowParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCopyTestflowParams() *CopyTestflowParams {
	return &CopyTestflowParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCopyTestflowParamsWithTimeout creates a new CopyTestflowParams object
// with the ability to set a timeout on a request.
func NewCopyTestflowParamsWithTimeout(timeout time.Duration) *CopyTestflowParams {
	return &CopyTestflowParams{
		timeout: timeout,
	}
}

// NewCopyTestflowParamsWithContext creates a new CopyTestflowParams object
// with the ability to set a context for a request.
func NewCopyTestflowParamsWithContext(ctx context.Context) *CopyTestflowParams {
	return &CopyTestflowParams{
		Context: ctx,
	}
}

// NewCopyTestflowParamsWithHTTPClient creates a new CopyTestflowParams object
// with the ability to set a custom HTTPClient for a request.
func NewCopyTestflowParamsWithHTTPClient(client *http.Client) *CopyTestflowParams {
	return &CopyTestflowParams{
		HTTPClient: client,
	}
}

/*
CopyTestflowParams contains all the parameters to send to the API endpoint

	for the copy testflow operation.

	Typically these are written to a http.Request.
*/
type CopyTestflowParams struct {

	/* CopyTestflow.

	   parameters for copy test flow
	*/
	CopyTestflow *models.CopyTestflow

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the copy testflow params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CopyTestflowParams) WithDefaults() *CopyTestflowParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the copy testflow params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CopyTestflowParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the copy testflow params
func (o *CopyTestflowParams) WithTimeout(timeout time.Duration) *CopyTestflowParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the copy testflow params
func (o *CopyTestflowParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the copy testflow params
func (o *CopyTestflowParams) WithContext(ctx context.Context) *CopyTestflowParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the copy testflow params
func (o *CopyTestflowParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the copy testflow params
func (o *CopyTestflowParams) WithHTTPClient(client *http.Client) *CopyTestflowParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the copy testflow params
func (o *CopyTestflowParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCopyTestflow adds the copyTestflow to the copy testflow params
func (o *CopyTestflowParams) WithCopyTestflow(copyTestflow *models.CopyTestflow) *CopyTestflowParams {
	o.SetCopyTestflow(copyTestflow)
	return o
}

// SetCopyTestflow adds the copyTestflow to the copy testflow params
func (o *CopyTestflowParams) SetCopyTestflow(copyTestflow *models.CopyTestflow) {
	o.CopyTestflow = copyTestflow
}

// WriteToRequest writes these params to a swagger request
func (o *CopyTestflowParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.CopyTestflow != nil {
		if err := r.SetBodyParam(o.CopyTestflow); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
