// Code generated by go-swagger; DO NOT EDIT.

package testflow

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ipfs-force-community/brightbird/models"
)

// CountTestFlowRequestReader is a Reader for the CountTestFlowRequest structure.
type CountTestFlowRequestReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CountTestFlowRequestReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCountTestFlowRequestOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 503:
		result := NewCountTestFlowRequestServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /testflow/count] countTestFlowRequest", response, response.Code())
	}
}

// NewCountTestFlowRequestOK creates a CountTestFlowRequestOK with default headers values
func NewCountTestFlowRequestOK() *CountTestFlowRequestOK {
	return &CountTestFlowRequestOK{}
}

/*
CountTestFlowRequestOK describes a response with status code 200, with default header values.

CountTestFlowRequestOK count test flow request o k
*/
type CountTestFlowRequestOK struct {
}

// IsSuccess returns true when this count test flow request o k response has a 2xx status code
func (o *CountTestFlowRequestOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this count test flow request o k response has a 3xx status code
func (o *CountTestFlowRequestOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this count test flow request o k response has a 4xx status code
func (o *CountTestFlowRequestOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this count test flow request o k response has a 5xx status code
func (o *CountTestFlowRequestOK) IsServerError() bool {
	return false
}

// IsCode returns true when this count test flow request o k response a status code equal to that given
func (o *CountTestFlowRequestOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the count test flow request o k response
func (o *CountTestFlowRequestOK) Code() int {
	return 200
}

func (o *CountTestFlowRequestOK) Error() string {
	return fmt.Sprintf("[GET /testflow/count][%d] countTestFlowRequestOK ", 200)
}

func (o *CountTestFlowRequestOK) String() string {
	return fmt.Sprintf("[GET /testflow/count][%d] countTestFlowRequestOK ", 200)
}

func (o *CountTestFlowRequestOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCountTestFlowRequestServiceUnavailable creates a CountTestFlowRequestServiceUnavailable with default headers values
func NewCountTestFlowRequestServiceUnavailable() *CountTestFlowRequestServiceUnavailable {
	return &CountTestFlowRequestServiceUnavailable{}
}

/*
CountTestFlowRequestServiceUnavailable describes a response with status code 503, with default header values.

apiError
*/
type CountTestFlowRequestServiceUnavailable struct {
	Payload *models.APIError
}

// IsSuccess returns true when this count test flow request service unavailable response has a 2xx status code
func (o *CountTestFlowRequestServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this count test flow request service unavailable response has a 3xx status code
func (o *CountTestFlowRequestServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this count test flow request service unavailable response has a 4xx status code
func (o *CountTestFlowRequestServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this count test flow request service unavailable response has a 5xx status code
func (o *CountTestFlowRequestServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this count test flow request service unavailable response a status code equal to that given
func (o *CountTestFlowRequestServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the count test flow request service unavailable response
func (o *CountTestFlowRequestServiceUnavailable) Code() int {
	return 503
}

func (o *CountTestFlowRequestServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /testflow/count][%d] countTestFlowRequestServiceUnavailable  %+v", 503, o.Payload)
}

func (o *CountTestFlowRequestServiceUnavailable) String() string {
	return fmt.Sprintf("[GET /testflow/count][%d] countTestFlowRequestServiceUnavailable  %+v", 503, o.Payload)
}

func (o *CountTestFlowRequestServiceUnavailable) GetPayload() *models.APIError {
	return o.Payload
}

func (o *CountTestFlowRequestServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
