// Code generated by go-swagger; DO NOT EDIT.

package testflow

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hunjixin/brightbird/models"
)

// GetTestFlowReader is a Reader for the GetTestFlow structure.
type GetTestFlowReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTestFlowReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTestFlowOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 503:
		result := NewGetTestFlowServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetTestFlowOK creates a GetTestFlowOK with default headers values
func NewGetTestFlowOK() *GetTestFlowOK {
	return &GetTestFlowOK{}
}

/*
GetTestFlowOK describes a response with status code 200, with default header values.

testFlow
*/
type GetTestFlowOK struct {
	Payload *models.TestFlow
}

// IsSuccess returns true when this get test flow o k response has a 2xx status code
func (o *GetTestFlowOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get test flow o k response has a 3xx status code
func (o *GetTestFlowOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get test flow o k response has a 4xx status code
func (o *GetTestFlowOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get test flow o k response has a 5xx status code
func (o *GetTestFlowOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get test flow o k response a status code equal to that given
func (o *GetTestFlowOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get test flow o k response
func (o *GetTestFlowOK) Code() int {
	return 200
}

func (o *GetTestFlowOK) Error() string {
	return fmt.Sprintf("[GET /testflow][%d] getTestFlowOK  %+v", 200, o.Payload)
}

func (o *GetTestFlowOK) String() string {
	return fmt.Sprintf("[GET /testflow][%d] getTestFlowOK  %+v", 200, o.Payload)
}

func (o *GetTestFlowOK) GetPayload() *models.TestFlow {
	return o.Payload
}

func (o *GetTestFlowOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TestFlow)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTestFlowServiceUnavailable creates a GetTestFlowServiceUnavailable with default headers values
func NewGetTestFlowServiceUnavailable() *GetTestFlowServiceUnavailable {
	return &GetTestFlowServiceUnavailable{}
}

/*
GetTestFlowServiceUnavailable describes a response with status code 503, with default header values.

apiError
*/
type GetTestFlowServiceUnavailable struct {
	Payload *models.APIError
}

// IsSuccess returns true when this get test flow service unavailable response has a 2xx status code
func (o *GetTestFlowServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get test flow service unavailable response has a 3xx status code
func (o *GetTestFlowServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get test flow service unavailable response has a 4xx status code
func (o *GetTestFlowServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this get test flow service unavailable response has a 5xx status code
func (o *GetTestFlowServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this get test flow service unavailable response a status code equal to that given
func (o *GetTestFlowServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the get test flow service unavailable response
func (o *GetTestFlowServiceUnavailable) Code() int {
	return 503
}

func (o *GetTestFlowServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /testflow][%d] getTestFlowServiceUnavailable  %+v", 503, o.Payload)
}

func (o *GetTestFlowServiceUnavailable) String() string {
	return fmt.Sprintf("[GET /testflow][%d] getTestFlowServiceUnavailable  %+v", 503, o.Payload)
}

func (o *GetTestFlowServiceUnavailable) GetPayload() *models.APIError {
	return o.Payload
}

func (o *GetTestFlowServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
