// Code generated by go-swagger; DO NOT EDIT.

package testflow

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTestFlowRequestParams creates a new GetTestFlowRequestParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetTestFlowRequestParams() *GetTestFlowRequestParams {
	return &GetTestFlowRequestParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetTestFlowRequestParamsWithTimeout creates a new GetTestFlowRequestParams object
// with the ability to set a timeout on a request.
func NewGetTestFlowRequestParamsWithTimeout(timeout time.Duration) *GetTestFlowRequestParams {
	return &GetTestFlowRequestParams{
		timeout: timeout,
	}
}

// NewGetTestFlowRequestParamsWithContext creates a new GetTestFlowRequestParams object
// with the ability to set a context for a request.
func NewGetTestFlowRequestParamsWithContext(ctx context.Context) *GetTestFlowRequestParams {
	return &GetTestFlowRequestParams{
		Context: ctx,
	}
}

// NewGetTestFlowRequestParamsWithHTTPClient creates a new GetTestFlowRequestParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetTestFlowRequestParamsWithHTTPClient(client *http.Client) *GetTestFlowRequestParams {
	return &GetTestFlowRequestParams{
		HTTPClient: client,
	}
}

/*
GetTestFlowRequestParams contains all the parameters to send to the API endpoint

	for the get test flow request operation.

	Typically these are written to a http.Request.
*/
type GetTestFlowRequestParams struct {

	/* ID.

	   id of testflow
	*/
	ID *string

	/* Name.

	   name of testflow
	*/
	Name *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get test flow request params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTestFlowRequestParams) WithDefaults() *GetTestFlowRequestParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get test flow request params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTestFlowRequestParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get test flow request params
func (o *GetTestFlowRequestParams) WithTimeout(timeout time.Duration) *GetTestFlowRequestParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get test flow request params
func (o *GetTestFlowRequestParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get test flow request params
func (o *GetTestFlowRequestParams) WithContext(ctx context.Context) *GetTestFlowRequestParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get test flow request params
func (o *GetTestFlowRequestParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get test flow request params
func (o *GetTestFlowRequestParams) WithHTTPClient(client *http.Client) *GetTestFlowRequestParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get test flow request params
func (o *GetTestFlowRequestParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get test flow request params
func (o *GetTestFlowRequestParams) WithID(id *string) *GetTestFlowRequestParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get test flow request params
func (o *GetTestFlowRequestParams) SetID(id *string) {
	o.ID = id
}

// WithName adds the name to the get test flow request params
func (o *GetTestFlowRequestParams) WithName(name *string) *GetTestFlowRequestParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get test flow request params
func (o *GetTestFlowRequestParams) SetName(name *string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetTestFlowRequestParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ID != nil {

		// query param id
		var qrID string

		if o.ID != nil {
			qrID = *o.ID
		}
		qID := qrID
		if qID != "" {

			if err := r.SetQueryParam("id", qID); err != nil {
				return err
			}
		}
	}

	if o.Name != nil {

		// query param name
		var qrName string

		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {

			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
