// Code generated by go-swagger; DO NOT EDIT.

package testflow

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hunjixin/brightbird/models"
)

// ListTestFlowsReader is a Reader for the ListTestFlows structure.
type ListTestFlowsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListTestFlowsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListTestFlowsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 503:
		result := NewListTestFlowsServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListTestFlowsOK creates a ListTestFlowsOK with default headers values
func NewListTestFlowsOK() *ListTestFlowsOK {
	return &ListTestFlowsOK{}
}

/*
ListTestFlowsOK describes a response with status code 200, with default header values.

listTestFlowResp
*/
type ListTestFlowsOK struct {
	Payload *models.ListTestFlowResp
}

// IsSuccess returns true when this list test flows o k response has a 2xx status code
func (o *ListTestFlowsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list test flows o k response has a 3xx status code
func (o *ListTestFlowsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list test flows o k response has a 4xx status code
func (o *ListTestFlowsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list test flows o k response has a 5xx status code
func (o *ListTestFlowsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list test flows o k response a status code equal to that given
func (o *ListTestFlowsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list test flows o k response
func (o *ListTestFlowsOK) Code() int {
	return 200
}

func (o *ListTestFlowsOK) Error() string {
	return fmt.Sprintf("[GET /testflow/list][%d] listTestFlowsOK  %+v", 200, o.Payload)
}

func (o *ListTestFlowsOK) String() string {
	return fmt.Sprintf("[GET /testflow/list][%d] listTestFlowsOK  %+v", 200, o.Payload)
}

func (o *ListTestFlowsOK) GetPayload() *models.ListTestFlowResp {
	return o.Payload
}

func (o *ListTestFlowsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ListTestFlowResp)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListTestFlowsServiceUnavailable creates a ListTestFlowsServiceUnavailable with default headers values
func NewListTestFlowsServiceUnavailable() *ListTestFlowsServiceUnavailable {
	return &ListTestFlowsServiceUnavailable{}
}

/*
ListTestFlowsServiceUnavailable describes a response with status code 503, with default header values.

apiError
*/
type ListTestFlowsServiceUnavailable struct {
	Payload *models.APIError
}

// IsSuccess returns true when this list test flows service unavailable response has a 2xx status code
func (o *ListTestFlowsServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list test flows service unavailable response has a 3xx status code
func (o *ListTestFlowsServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list test flows service unavailable response has a 4xx status code
func (o *ListTestFlowsServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this list test flows service unavailable response has a 5xx status code
func (o *ListTestFlowsServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this list test flows service unavailable response a status code equal to that given
func (o *ListTestFlowsServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the list test flows service unavailable response
func (o *ListTestFlowsServiceUnavailable) Code() int {
	return 503
}

func (o *ListTestFlowsServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /testflow/list][%d] listTestFlowsServiceUnavailable  %+v", 503, o.Payload)
}

func (o *ListTestFlowsServiceUnavailable) String() string {
	return fmt.Sprintf("[GET /testflow/list][%d] listTestFlowsServiceUnavailable  %+v", 503, o.Payload)
}

func (o *ListTestFlowsServiceUnavailable) GetPayload() *models.APIError {
	return o.Payload
}

func (o *ListTestFlowsServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
