// Code generated by go-swagger; DO NOT EDIT.

package testflow

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ipfs-force-community/brightbird/models"
)

// ListInGroupRequestReader is a Reader for the ListInGroupRequest structure.
type ListInGroupRequestReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListInGroupRequestReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListInGroupRequestOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 503:
		result := NewListInGroupRequestServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /testflow/list] listInGroupRequest", response, response.Code())
	}
}

// NewListInGroupRequestOK creates a ListInGroupRequestOK with default headers values
func NewListInGroupRequestOK() *ListInGroupRequestOK {
	return &ListInGroupRequestOK{}
}

/*
ListInGroupRequestOK describes a response with status code 200, with default header values.

listTestFlowResp
*/
type ListInGroupRequestOK struct {
	Payload *models.ListTestFlowResp
}

// IsSuccess returns true when this list in group request o k response has a 2xx status code
func (o *ListInGroupRequestOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list in group request o k response has a 3xx status code
func (o *ListInGroupRequestOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list in group request o k response has a 4xx status code
func (o *ListInGroupRequestOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list in group request o k response has a 5xx status code
func (o *ListInGroupRequestOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list in group request o k response a status code equal to that given
func (o *ListInGroupRequestOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list in group request o k response
func (o *ListInGroupRequestOK) Code() int {
	return 200
}

func (o *ListInGroupRequestOK) Error() string {
	return fmt.Sprintf("[GET /testflow/list][%d] listInGroupRequestOK  %+v", 200, o.Payload)
}

func (o *ListInGroupRequestOK) String() string {
	return fmt.Sprintf("[GET /testflow/list][%d] listInGroupRequestOK  %+v", 200, o.Payload)
}

func (o *ListInGroupRequestOK) GetPayload() *models.ListTestFlowResp {
	return o.Payload
}

func (o *ListInGroupRequestOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ListTestFlowResp)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListInGroupRequestServiceUnavailable creates a ListInGroupRequestServiceUnavailable with default headers values
func NewListInGroupRequestServiceUnavailable() *ListInGroupRequestServiceUnavailable {
	return &ListInGroupRequestServiceUnavailable{}
}

/*
ListInGroupRequestServiceUnavailable describes a response with status code 503, with default header values.

apiError
*/
type ListInGroupRequestServiceUnavailable struct {
	Payload *models.APIError
}

// IsSuccess returns true when this list in group request service unavailable response has a 2xx status code
func (o *ListInGroupRequestServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list in group request service unavailable response has a 3xx status code
func (o *ListInGroupRequestServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list in group request service unavailable response has a 4xx status code
func (o *ListInGroupRequestServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this list in group request service unavailable response has a 5xx status code
func (o *ListInGroupRequestServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this list in group request service unavailable response a status code equal to that given
func (o *ListInGroupRequestServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the list in group request service unavailable response
func (o *ListInGroupRequestServiceUnavailable) Code() int {
	return 503
}

func (o *ListInGroupRequestServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /testflow/list][%d] listInGroupRequestServiceUnavailable  %+v", 503, o.Payload)
}

func (o *ListInGroupRequestServiceUnavailable) String() string {
	return fmt.Sprintf("[GET /testflow/list][%d] listInGroupRequestServiceUnavailable  %+v", 503, o.Payload)
}

func (o *ListInGroupRequestServiceUnavailable) GetPayload() *models.APIError {
	return o.Payload
}

func (o *ListInGroupRequestServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
