// Code generated by go-swagger; DO NOT EDIT.

package testflow

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewListTestFlowsParams creates a new ListTestFlowsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListTestFlowsParams() *ListTestFlowsParams {
	return &ListTestFlowsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListTestFlowsParamsWithTimeout creates a new ListTestFlowsParams object
// with the ability to set a timeout on a request.
func NewListTestFlowsParamsWithTimeout(timeout time.Duration) *ListTestFlowsParams {
	return &ListTestFlowsParams{
		timeout: timeout,
	}
}

// NewListTestFlowsParamsWithContext creates a new ListTestFlowsParams object
// with the ability to set a context for a request.
func NewListTestFlowsParamsWithContext(ctx context.Context) *ListTestFlowsParams {
	return &ListTestFlowsParams{
		Context: ctx,
	}
}

// NewListTestFlowsParamsWithHTTPClient creates a new ListTestFlowsParams object
// with the ability to set a custom HTTPClient for a request.
func NewListTestFlowsParamsWithHTTPClient(client *http.Client) *ListTestFlowsParams {
	return &ListTestFlowsParams{
		HTTPClient: client,
	}
}

/*
ListTestFlowsParams contains all the parameters to send to the API endpoint

	for the list test flows operation.

	Typically these are written to a http.Request.
*/
type ListTestFlowsParams struct {

	/* GroupID.

	   group id  of test flow
	*/
	GroupID *string

	/* PageNum.

	   page number  of test flow
	*/
	PageNum *int64

	/* PageSize.

	   page size  of test flow
	*/
	PageSize *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list test flows params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListTestFlowsParams) WithDefaults() *ListTestFlowsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list test flows params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListTestFlowsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list test flows params
func (o *ListTestFlowsParams) WithTimeout(timeout time.Duration) *ListTestFlowsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list test flows params
func (o *ListTestFlowsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list test flows params
func (o *ListTestFlowsParams) WithContext(ctx context.Context) *ListTestFlowsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list test flows params
func (o *ListTestFlowsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list test flows params
func (o *ListTestFlowsParams) WithHTTPClient(client *http.Client) *ListTestFlowsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list test flows params
func (o *ListTestFlowsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGroupID adds the groupID to the list test flows params
func (o *ListTestFlowsParams) WithGroupID(groupID *string) *ListTestFlowsParams {
	o.SetGroupID(groupID)
	return o
}

// SetGroupID adds the groupId to the list test flows params
func (o *ListTestFlowsParams) SetGroupID(groupID *string) {
	o.GroupID = groupID
}

// WithPageNum adds the pageNum to the list test flows params
func (o *ListTestFlowsParams) WithPageNum(pageNum *int64) *ListTestFlowsParams {
	o.SetPageNum(pageNum)
	return o
}

// SetPageNum adds the pageNum to the list test flows params
func (o *ListTestFlowsParams) SetPageNum(pageNum *int64) {
	o.PageNum = pageNum
}

// WithPageSize adds the pageSize to the list test flows params
func (o *ListTestFlowsParams) WithPageSize(pageSize *int64) *ListTestFlowsParams {
	o.SetPageSize(pageSize)
	return o
}

// SetPageSize adds the pageSize to the list test flows params
func (o *ListTestFlowsParams) SetPageSize(pageSize *int64) {
	o.PageSize = pageSize
}

// WriteToRequest writes these params to a swagger request
func (o *ListTestFlowsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.GroupID != nil {

		// query param groupId
		var qrGroupID string

		if o.GroupID != nil {
			qrGroupID = *o.GroupID
		}
		qGroupID := qrGroupID
		if qGroupID != "" {

			if err := r.SetQueryParam("groupId", qGroupID); err != nil {
				return err
			}
		}
	}

	if o.PageNum != nil {

		// query param pageNum
		var qrPageNum int64

		if o.PageNum != nil {
			qrPageNum = *o.PageNum
		}
		qPageNum := swag.FormatInt64(qrPageNum)
		if qPageNum != "" {

			if err := r.SetQueryParam("pageNum", qPageNum); err != nil {
				return err
			}
		}
	}

	if o.PageSize != nil {

		// query param pageSize
		var qrPageSize int64

		if o.PageSize != nil {
			qrPageSize = *o.PageSize
		}
		qPageSize := swag.FormatInt64(qrPageSize)
		if qPageSize != "" {

			if err := r.SetQueryParam("pageSize", qPageSize); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
