apiVersion: v1
kind: Service
metadata:
  name: venus-messager-{{.UniqueId}}-svc
spec:
  clusterIP: None
  selector:
    app: venus-messager-{{.UniqueId}}-pod
  ports:
    - protocol: TCP
      port: 39812