# 基于Node的镜像来构建Vue项目
FROM node:latest as build-stage

# 设置工作目录
WORKDIR /app

# 复制项目文件
COPY . /app

# 安装项目依赖
RUN apt update && apt install make -y

RUN cd web/ui/ && yarn install

# 构建应用
RUN make ui

# 用nginx来部署Vue应用
FROM nginx:stable as production-stage

# 从构建阶段复制构建结果到nginx的服务目录下
COPY --from=build-stage /app/dist/front /usr/share/nginx/html
COPY web/ui/nginx-http.conf /etc/nginx/conf.d/default.conf

# 开放80端口
EXPOSE 80

# 当容器启动时运行nginx
CMD ["nginx", "-g", "daemon off;"]
