apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: droplet-market-ttttttt-deployment
spec:
  replicas: 1
  serviceName: droplet-market-ttttttt-svc
  selector:
    matchLabels:
      app: droplet-market-ttttttt-pod
  template:
    metadata:
      labels:
        app: droplet-market-ttttttt-pod
    spec:
      containers:
        - name: droplet-market-ttttttt
          image: "192.168.200.175/filvenus/droplet:4985556f19f530f510b92108d9a4fb7146b306d1"
          command: 
            - "sleep"
            - "604800"
          ports:
            - containerPort: 41235
              protocol: TCP
            - containerPort: 58418
              protocol: TCP
          volumeMounts:
            - mountPath: /root
              name: droplet-market-pvc
            - name: marketcfg
              mountPath: "/root/config.tmp"
              subPath: "config.toml"
            - mountPath: /shared-dir
              name: shared-dir-v
              subPath: zsk
      volumes:
        - name: marketcfg
          configMap:
            name: droplet-market-cfg-b447c387b9d7121a
            items:
              - key: config.toml
                path: config.toml
        - name: shared-dir-v
          persistentVolumeClaim:
            claimName: shared-dir
  volumeClaimTemplates:
    - metadata:
        name: droplet-market-pvc # name+podname
        labels:
          app: droplet-market-b447c387b9d7121a-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "nfs-client"
        resources:
          requests:
            storage: 1Gi