apiVersion: v1
data:
  config.toml: |
    [api]
      Address = "/ip4/0.0.0.0/tcp/39812"

    [db]
      type = "{{if gt (len .MysqlDSN) 0}}mysql{{else}}sqlite{{end}}"

      [db.mysql]
        connMaxLifeTime = "1m0s"
        connectionString = "{{.MysqlDSN}}"
        debug = false
        maxIdleConn = 10
        maxOpenConn = 10

      [db.sqlite]
        debug = false

    [gateway]
      token = "{{.AuthToken}}"
      url = [{{.GatewayUrl}}]

    [jwt]
      authURL = "{{.AuthUrl}}"
      token = "{{.AuthToken}}"

    [libp2p]
      bootstrapAddresses = []
      expandPeriod = "0s"
      listenAddresses = "/ip4/0.0.0.0/tcp/0"
      minPeerThreshold = 0

    [log]
      level = "info"
      path = ""

    [messageService]
      DefaultTimeout = "1s"
      EstimateMessageTimeout = "5s"
      SignMessageTimeout = "3s"
      WaitingChainHeadStableDuration = "15s"
      skipProcessHead = true
      skipPushMessage = true

    [metrics]
      Enabled = false

      [metrics.Exporter]
        Type = "prometheus"

        [metrics.Exporter.Graphite]
          Host = "127.0.0.1"
          Namespace = ""
          Port = 4568
          ReportingPeriod = "10s"

        [metrics.Exporter.Prometheus]
          EndPoint = "/ip4/0.0.0.0/tcp/4568"
          Namespace = ""
          Path = "/debug/metrics"
          RegistryType = "define"
          ReportingPeriod = "10s"

    [node]
      token = "{{.AuthToken}}"
      url = "{{.NodeUrl}}"

    [publisher]
      cacheReleasePeriod = 0
      concurrency = 5
      enableMultiNode = true
      enablePubsub = false

    [rateLimit]
      redis = ""

    [tracing]
      JaegerEndpoint = "localhost:6831"
      JaegerTracingEnabled = false
      ProbabilitySampler = 1.0
      ServerName = ""

kind: ConfigMap
metadata:
  name: sophon-messager-cfg-{{.UniqueId}}