apiVersion: v1
kind: Service
metadata:
  name: droplet-market-{{.UniqueId}}-svc
spec:
  clusterIP: None
  selector:
    app: droplet-market-{{.UniqueId}}-pod
  ports:
    - protocol: TCP
      port: 41235
      name: api
    - protocol: TCP
      port: 58418
      name: libp2p

