apiVersion: v1
data:
  config.toml: |
    # Default config:
    SimultaneousTransfersForStorage = 20
    SimultaneousTransfersForStoragePerClient = 20
    SimultaneousTransfersForRetrieval = 20

    [API]
      ListenAddress = "/ip4/0.0.0.0/tcp/41235"
      RemoteListenAddress = ""
      Timeout = "30s"
      PrivateKey = "02c4bd06170805d981d082a70b0d22813043a0fc579ce2e07dcc2fb44471709d"

    [Libp2p]
      ListenAddresses = ["/ip4/0.0.0.0/tcp/58418", "/ip6/::/tcp/0"]
      AnnounceAddresses = []
      NoAnnounceAddresses = []
      PrivateKey = ""

    [Node]
      Url = "{{.NodeUrl}}"
      Token = "{{.UserToken}}"

    [Messager]
      Url = "{{.MessagerUrl}}"
      Token = "{{.UserToken}}"

    [Signer]
      Type = "gateway"
      Url = "{{.GatewayUrl}}"
      Token = "{{.UserToken}}"

    [AuthNode]
      Url = "{{.AuthUrl}}"
      Token = "{{.UserToken}}"

    [Mysql]
      ConnectionString = "{{.MysqlDSN}}"
      MaxOpenConn = 100
      MaxIdleConn = 100
      ConnMaxLifeTime = "1m"
      Debug = false

    [[PieceStorage.Fs]]
      Name = "local"
      ReadOnly = false
      Path = "/root/piece-{{.UniqueId}}"
     

    [DAGStore]
      RootDir = "/root/.droplet-market/dagstore"
      MaxConcurrentIndex = 5
      MaxConcurrentReadyFetches = 0
      MaxConcurrencyStorageCalls = 100
      GCInterval = "1m0s"
      Transient = ""
      Index = ""
      UseTransient = false

    [CommonProvider]
      ConsiderOnlineStorageDeals = true
      ConsiderOfflineStorageDeals = true
      ConsiderOnlineRetrievalDeals = true
      ConsiderOfflineRetrievalDeals = true
      ConsiderVerifiedStorageDeals = true
      ConsiderUnverifiedStorageDeals = true
      PieceCidBlocklist = []
      ExpectedSealDuration = "24h0m0s"
      MaxDealStartDelay = "336h0m0s"
      PublishMsgPeriod = "1h0m0s"
      MaxDealsPerPublishMsg = 8
      MaxProviderCollateralMultiplier = 2
      Filter = ""
      RetrievalFilter = ""
      TransferPath = ""
      MaxPublishDealsFee = "0 FIL"
      MaxMarketBalanceAddFee = "0 FIL"
      RetrievalPaymentAddress = ""
      [CommonProvider.RetrievalPricing]
        Strategy = "default"
        [CommonProvider.RetrievalPricing.Default]
          VerifiedDealsFreeTransfer = true
        [CommonProvider.RetrievalPricing.External]
          Path = ""

    [Journal]
      Path = "journal"

    [Metrics]
      Enabled = false
      [Metrics.Exporter]
        Type = "prometheus"
        [Metrics.Exporter.Prometheus]
          RegistryType = "define"
          Namespace = ""
          EndPoint = "/ip4/0.0.0.0/tcp/4568"
          Path = "/debug/metrics"
          ReportingPeriod = "10s"
        [Metrics.Exporter.Graphite]
          Namespace = ""
          Host = "127.0.0.1"
          Port = 4568
          ReportingPeriod = "10s"
kind: ConfigMap
metadata:
  name: droplet-market-cfg-{{.UniqueId}}