// Code generated by go-swagger; DO NOT EDIT.

package download

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDownloadParamsParams creates a new DownloadParamsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDownloadParamsParams() *DownloadParamsParams {
	return &DownloadParamsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDownloadParamsParamsWithTimeout creates a new DownloadParamsParams object
// with the ability to set a timeout on a request.
func NewDownloadParamsParamsWithTimeout(timeout time.Duration) *DownloadParamsParams {
	return &DownloadParamsParams{
		timeout: timeout,
	}
}

// NewDownloadParamsParamsWithContext creates a new DownloadParamsParams object
// with the ability to set a context for a request.
func NewDownloadParamsParamsWithContext(ctx context.Context) *DownloadParamsParams {
	return &DownloadParamsParams{
		Context: ctx,
	}
}

// NewDownloadParamsParamsWithHTTPClient creates a new DownloadParamsParams object
// with the ability to set a custom HTTPClient for a request.
func NewDownloadParamsParamsWithHTTPClient(client *http.Client) *DownloadParamsParams {
	return &DownloadParamsParams{
		HTTPClient: client,
	}
}

/*
DownloadParamsParams contains all the parameters to send to the API endpoint

	for the download params operation.

	Typically these are written to a http.Request.
*/
type DownloadParamsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the download params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DownloadParamsParams) WithDefaults() *DownloadParamsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the download params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DownloadParamsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the download params params
func (o *DownloadParamsParams) WithTimeout(timeout time.Duration) *DownloadParamsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the download params params
func (o *DownloadParamsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the download params params
func (o *DownloadParamsParams) WithContext(ctx context.Context) *DownloadParamsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the download params params
func (o *DownloadParamsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the download params params
func (o *DownloadParamsParams) WithHTTPClient(client *http.Client) *DownloadParamsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the download params params
func (o *DownloadParamsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *DownloadParamsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
