// Code generated by go-swagger; DO NOT EDIT.

package job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCountJobParams creates a new CountJobParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCountJobParams() *CountJobParams {
	return &CountJobParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCountJobParamsWithTimeout creates a new CountJobParams object
// with the ability to set a timeout on a request.
func NewCountJobParamsWithTimeout(timeout time.Duration) *CountJobParams {
	return &CountJobParams{
		timeout: timeout,
	}
}

// NewCountJobParamsWithContext creates a new CountJobParams object
// with the ability to set a context for a request.
func NewCountJobParamsWithContext(ctx context.Context) *CountJobParams {
	return &CountJobParams{
		Context: ctx,
	}
}

// NewCountJobParamsWithHTTPClient creates a new CountJobParams object
// with the ability to set a custom HTTPClient for a request.
func NewCountJobParamsWithHTTPClient(client *http.Client) *CountJobParams {
	return &CountJobParams{
		HTTPClient: client,
	}
}

/*
CountJobParams contains all the parameters to send to the API endpoint

	for the count job operation.

	Typically these are written to a http.Request.
*/
type CountJobParams struct {

	/* ID.

	   job id
	*/
	ID *string

	/* Name.

	   job name
	*/
	Name *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the count job params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CountJobParams) WithDefaults() *CountJobParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the count job params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CountJobParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the count job params
func (o *CountJobParams) WithTimeout(timeout time.Duration) *CountJobParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the count job params
func (o *CountJobParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the count job params
func (o *CountJobParams) WithContext(ctx context.Context) *CountJobParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the count job params
func (o *CountJobParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the count job params
func (o *CountJobParams) WithHTTPClient(client *http.Client) *CountJobParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the count job params
func (o *CountJobParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the count job params
func (o *CountJobParams) WithID(id *string) *CountJobParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the count job params
func (o *CountJobParams) SetID(id *string) {
	o.ID = id
}

// WithName adds the name to the count job params
func (o *CountJobParams) WithName(name *string) *CountJobParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the count job params
func (o *CountJobParams) SetName(name *string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *CountJobParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ID != nil {

		// query param id
		var qrID string

		if o.ID != nil {
			qrID = *o.ID
		}
		qID := qrID
		if qID != "" {

			if err := r.SetQueryParam("id", qID); err != nil {
				return err
			}
		}
	}

	if o.Name != nil {

		// query param name
		var qrName string

		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {

			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
