// Code generated by go-swagger; DO NOT EDIT.

package job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hunjixin/brightbird/models"
)

// CountJobRequestReader is a Reader for the CountJobRequest structure.
type CountJobRequestReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CountJobRequestReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCountJobRequestOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 503:
		result := NewCountJobRequestServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCountJobRequestOK creates a CountJobRequestOK with default headers values
func NewCountJobRequestOK() *CountJobRequestOK {
	return &CountJobRequestOK{}
}

/*
CountJobRequestOK describes a response with status code 200, with default header values.

listJobResp
*/
type CountJobRequestOK struct {
	Payload models.ListJobResp
}

// IsSuccess returns true when this count job request o k response has a 2xx status code
func (o *CountJobRequestOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this count job request o k response has a 3xx status code
func (o *CountJobRequestOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this count job request o k response has a 4xx status code
func (o *CountJobRequestOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this count job request o k response has a 5xx status code
func (o *CountJobRequestOK) IsServerError() bool {
	return false
}

// IsCode returns true when this count job request o k response a status code equal to that given
func (o *CountJobRequestOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the count job request o k response
func (o *CountJobRequestOK) Code() int {
	return 200
}

func (o *CountJobRequestOK) Error() string {
	return fmt.Sprintf("[GET /job/count][%d] countJobRequestOK  %+v", 200, o.Payload)
}

func (o *CountJobRequestOK) String() string {
	return fmt.Sprintf("[GET /job/count][%d] countJobRequestOK  %+v", 200, o.Payload)
}

func (o *CountJobRequestOK) GetPayload() models.ListJobResp {
	return o.Payload
}

func (o *CountJobRequestOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCountJobRequestServiceUnavailable creates a CountJobRequestServiceUnavailable with default headers values
func NewCountJobRequestServiceUnavailable() *CountJobRequestServiceUnavailable {
	return &CountJobRequestServiceUnavailable{}
}

/*
CountJobRequestServiceUnavailable describes a response with status code 503, with default header values.

apiError
*/
type CountJobRequestServiceUnavailable struct {
	Payload *models.APIError
}

// IsSuccess returns true when this count job request service unavailable response has a 2xx status code
func (o *CountJobRequestServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this count job request service unavailable response has a 3xx status code
func (o *CountJobRequestServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this count job request service unavailable response has a 4xx status code
func (o *CountJobRequestServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this count job request service unavailable response has a 5xx status code
func (o *CountJobRequestServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this count job request service unavailable response a status code equal to that given
func (o *CountJobRequestServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the count job request service unavailable response
func (o *CountJobRequestServiceUnavailable) Code() int {
	return 503
}

func (o *CountJobRequestServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /job/count][%d] countJobRequestServiceUnavailable  %+v", 503, o.Payload)
}

func (o *CountJobRequestServiceUnavailable) String() string {
	return fmt.Sprintf("[GET /job/count][%d] countJobRequestServiceUnavailable  %+v", 503, o.Payload)
}

func (o *CountJobRequestServiceUnavailable) GetPayload() *models.APIError {
	return o.Payload
}

func (o *CountJobRequestServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
