// Code generated by go-swagger; DO NOT EDIT.

package job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hunjixin/brightbird/models"
)

// CountJobReader is a Reader for the CountJob structure.
type CountJobReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CountJobReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCountJobOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 503:
		result := NewCountJobServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCountJobOK creates a CountJobOK with default headers values
func NewCountJobOK() *CountJobOK {
	return &CountJobOK{}
}

/*
CountJobOK describes a response with status code 200, with default header values.

listJobResp
*/
type CountJobOK struct {
	Payload models.ListJobResp
}

// IsSuccess returns true when this count job o k response has a 2xx status code
func (o *CountJobOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this count job o k response has a 3xx status code
func (o *CountJobOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this count job o k response has a 4xx status code
func (o *CountJobOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this count job o k response has a 5xx status code
func (o *CountJobOK) IsServerError() bool {
	return false
}

// IsCode returns true when this count job o k response a status code equal to that given
func (o *CountJobOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the count job o k response
func (o *CountJobOK) Code() int {
	return 200
}

func (o *CountJobOK) Error() string {
	return fmt.Sprintf("[GET /job/count][%d] countJobOK  %+v", 200, o.Payload)
}

func (o *CountJobOK) String() string {
	return fmt.Sprintf("[GET /job/count][%d] countJobOK  %+v", 200, o.Payload)
}

func (o *CountJobOK) GetPayload() models.ListJobResp {
	return o.Payload
}

func (o *CountJobOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCountJobServiceUnavailable creates a CountJobServiceUnavailable with default headers values
func NewCountJobServiceUnavailable() *CountJobServiceUnavailable {
	return &CountJobServiceUnavailable{}
}

/*
CountJobServiceUnavailable describes a response with status code 503, with default header values.

apiError
*/
type CountJobServiceUnavailable struct {
	Payload *models.APIError
}

// IsSuccess returns true when this count job service unavailable response has a 2xx status code
func (o *CountJobServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this count job service unavailable response has a 3xx status code
func (o *CountJobServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this count job service unavailable response has a 4xx status code
func (o *CountJobServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this count job service unavailable response has a 5xx status code
func (o *CountJobServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this count job service unavailable response a status code equal to that given
func (o *CountJobServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the count job service unavailable response
func (o *CountJobServiceUnavailable) Code() int {
	return 503
}

func (o *CountJobServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /job/count][%d] countJobServiceUnavailable  %+v", 503, o.Payload)
}

func (o *CountJobServiceUnavailable) String() string {
	return fmt.Sprintf("[GET /job/count][%d] countJobServiceUnavailable  %+v", 503, o.Payload)
}

func (o *CountJobServiceUnavailable) GetPayload() *models.APIError {
	return o.Payload
}

func (o *CountJobServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
