// Code generated by go-swagger; DO NOT EDIT.

package job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ipfs-force-community/brightbird/models"
)

// GetJobReader is a Reader for the GetJob structure.
type GetJobReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetJobReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetJobOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 503:
		result := NewGetJobServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /job/detail/{id}] getJob", response, response.Code())
	}
}

// NewGetJobOK creates a GetJobOK with default headers values
func NewGetJobOK() *GetJobOK {
	return &GetJobOK{}
}

/*
GetJobOK describes a response with status code 200, with default header values.

jobDetailResp
*/
type GetJobOK struct {
	Payload *models.JobDetailResp
}

// IsSuccess returns true when this get job o k response has a 2xx status code
func (o *GetJobOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get job o k response has a 3xx status code
func (o *GetJobOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get job o k response has a 4xx status code
func (o *GetJobOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get job o k response has a 5xx status code
func (o *GetJobOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get job o k response a status code equal to that given
func (o *GetJobOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get job o k response
func (o *GetJobOK) Code() int {
	return 200
}

func (o *GetJobOK) Error() string {
	return fmt.Sprintf("[GET /job/detail/{id}][%d] getJobOK  %+v", 200, o.Payload)
}

func (o *GetJobOK) String() string {
	return fmt.Sprintf("[GET /job/detail/{id}][%d] getJobOK  %+v", 200, o.Payload)
}

func (o *GetJobOK) GetPayload() *models.JobDetailResp {
	return o.Payload
}

func (o *GetJobOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JobDetailResp)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetJobServiceUnavailable creates a GetJobServiceUnavailable with default headers values
func NewGetJobServiceUnavailable() *GetJobServiceUnavailable {
	return &GetJobServiceUnavailable{}
}

/*
GetJobServiceUnavailable describes a response with status code 503, with default header values.

apiError
*/
type GetJobServiceUnavailable struct {
	Payload *models.APIError
}

// IsSuccess returns true when this get job service unavailable response has a 2xx status code
func (o *GetJobServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get job service unavailable response has a 3xx status code
func (o *GetJobServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get job service unavailable response has a 4xx status code
func (o *GetJobServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this get job service unavailable response has a 5xx status code
func (o *GetJobServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this get job service unavailable response a status code equal to that given
func (o *GetJobServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the get job service unavailable response
func (o *GetJobServiceUnavailable) Code() int {
	return 503
}

func (o *GetJobServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /job/detail/{id}][%d] getJobServiceUnavailable  %+v", 503, o.Payload)
}

func (o *GetJobServiceUnavailable) String() string {
	return fmt.Sprintf("[GET /job/detail/{id}][%d] getJobServiceUnavailable  %+v", 503, o.Payload)
}

func (o *GetJobServiceUnavailable) GetPayload() *models.APIError {
	return o.Payload
}

func (o *GetJobServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
