// Code generated by go-swagger; DO NOT EDIT.

package job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewJobNextNReqParams creates a new JobNextNReqParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewJobNextNReqParams() *JobNextNReqParams {
	return &JobNextNReqParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewJobNextNReqParamsWithTimeout creates a new JobNextNReqParams object
// with the ability to set a timeout on a request.
func NewJobNextNReqParamsWithTimeout(timeout time.Duration) *JobNextNReqParams {
	return &JobNextNReqParams{
		timeout: timeout,
	}
}

// NewJobNextNReqParamsWithContext creates a new JobNextNReqParams object
// with the ability to set a context for a request.
func NewJobNextNReqParamsWithContext(ctx context.Context) *JobNextNReqParams {
	return &JobNextNReqParams{
		Context: ctx,
	}
}

// NewJobNextNReqParamsWithHTTPClient creates a new JobNextNReqParams object
// with the ability to set a custom HTTPClient for a request.
func NewJobNextNReqParamsWithHTTPClient(client *http.Client) *JobNextNReqParams {
	return &JobNextNReqParams{
		HTTPClient: client,
	}
}

/*
JobNextNReqParams contains all the parameters to send to the API endpoint

	for the job next n req operation.

	Typically these are written to a http.Request.
*/
type JobNextNReqParams struct {

	// ID.
	ID *string

	// N.
	//
	// Format: int64
	N *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the job next n req params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *JobNextNReqParams) WithDefaults() *JobNextNReqParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the job next n req params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *JobNextNReqParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the job next n req params
func (o *JobNextNReqParams) WithTimeout(timeout time.Duration) *JobNextNReqParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the job next n req params
func (o *JobNextNReqParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the job next n req params
func (o *JobNextNReqParams) WithContext(ctx context.Context) *JobNextNReqParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the job next n req params
func (o *JobNextNReqParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the job next n req params
func (o *JobNextNReqParams) WithHTTPClient(client *http.Client) *JobNextNReqParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the job next n req params
func (o *JobNextNReqParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the job next n req params
func (o *JobNextNReqParams) WithID(id *string) *JobNextNReqParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the job next n req params
func (o *JobNextNReqParams) SetID(id *string) {
	o.ID = id
}

// WithN adds the n to the job next n req params
func (o *JobNextNReqParams) WithN(n *int64) *JobNextNReqParams {
	o.SetN(n)
	return o
}

// SetN adds the n to the job next n req params
func (o *JobNextNReqParams) SetN(n *int64) {
	o.N = n
}

// WriteToRequest writes these params to a swagger request
func (o *JobNextNReqParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ID != nil {

		// query param id
		var qrID string

		if o.ID != nil {
			qrID = *o.ID
		}
		qID := qrID
		if qID != "" {

			if err := r.SetQueryParam("id", qID); err != nil {
				return err
			}
		}
	}

	if o.N != nil {

		// query param n
		var qrN int64

		if o.N != nil {
			qrN = *o.N
		}
		qN := swag.FormatInt64(qrN)
		if qN != "" {

			if err := r.SetQueryParam("n", qN); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
