// Code generated by go-swagger; DO NOT EDIT.

package job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hunjixin/brightbird/models"
)

// ListJobsReader is a Reader for the ListJobs structure.
type ListJobsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListJobsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListJobsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 503:
		result := NewListJobsServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListJobsOK creates a ListJobsOK with default headers values
func NewListJobsOK() *ListJobsOK {
	return &ListJobsOK{}
}

/*
ListJobsOK describes a response with status code 200, with default header values.

listJobResp
*/
type ListJobsOK struct {
	Payload models.ListJobResp
}

// IsSuccess returns true when this list jobs o k response has a 2xx status code
func (o *ListJobsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list jobs o k response has a 3xx status code
func (o *ListJobsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list jobs o k response has a 4xx status code
func (o *ListJobsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list jobs o k response has a 5xx status code
func (o *ListJobsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list jobs o k response a status code equal to that given
func (o *ListJobsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list jobs o k response
func (o *ListJobsOK) Code() int {
	return 200
}

func (o *ListJobsOK) Error() string {
	return fmt.Sprintf("[GET /job/list][%d] listJobsOK  %+v", 200, o.Payload)
}

func (o *ListJobsOK) String() string {
	return fmt.Sprintf("[GET /job/list][%d] listJobsOK  %+v", 200, o.Payload)
}

func (o *ListJobsOK) GetPayload() models.ListJobResp {
	return o.Payload
}

func (o *ListJobsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListJobsServiceUnavailable creates a ListJobsServiceUnavailable with default headers values
func NewListJobsServiceUnavailable() *ListJobsServiceUnavailable {
	return &ListJobsServiceUnavailable{}
}

/*
ListJobsServiceUnavailable describes a response with status code 503, with default header values.

apiError
*/
type ListJobsServiceUnavailable struct {
	Payload *models.APIError
}

// IsSuccess returns true when this list jobs service unavailable response has a 2xx status code
func (o *ListJobsServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list jobs service unavailable response has a 3xx status code
func (o *ListJobsServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list jobs service unavailable response has a 4xx status code
func (o *ListJobsServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this list jobs service unavailable response has a 5xx status code
func (o *ListJobsServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this list jobs service unavailable response a status code equal to that given
func (o *ListJobsServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the list jobs service unavailable response
func (o *ListJobsServiceUnavailable) Code() int {
	return 503
}

func (o *ListJobsServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /job/list][%d] listJobsServiceUnavailable  %+v", 503, o.Payload)
}

func (o *ListJobsServiceUnavailable) String() string {
	return fmt.Sprintf("[GET /job/list][%d] listJobsServiceUnavailable  %+v", 503, o.Payload)
}

func (o *ListJobsServiceUnavailable) GetPayload() *models.APIError {
	return o.Payload
}

func (o *ListJobsServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
