apiVersion: v1
kind: Service
metadata:
  name: market-client-{{.UniqueId}}-svc
spec:
  type: ClusterIP
  selector:
    app: market-client-{{.UniqueId}}-pod
  ports:
    - protocol: TCP
      port: 41231
      name: api
    - protocol: TCP
      port: 34123
      name: libp2p

