// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ipfs-force-community/brightbird/models"
)

// DeleteTaskReader is a Reader for the DeleteTask structure.
type DeleteTaskReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteTaskReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteTaskOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 503:
		result := NewDeleteTaskServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /task/{id}] deleteTask", response, response.Code())
	}
}

// NewDeleteTaskOK creates a DeleteTaskOK with default headers values
func NewDeleteTaskOK() *DeleteTaskOK {
	return &DeleteTaskOK{}
}

/*
DeleteTaskOK describes a response with status code 200, with default header values.

DeleteTaskOK delete task o k
*/
type DeleteTaskOK struct {
}

// IsSuccess returns true when this delete task o k response has a 2xx status code
func (o *DeleteTaskOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete task o k response has a 3xx status code
func (o *DeleteTaskOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete task o k response has a 4xx status code
func (o *DeleteTaskOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete task o k response has a 5xx status code
func (o *DeleteTaskOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete task o k response a status code equal to that given
func (o *DeleteTaskOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete task o k response
func (o *DeleteTaskOK) Code() int {
	return 200
}

func (o *DeleteTaskOK) Error() string {
	return fmt.Sprintf("[DELETE /task/{id}][%d] deleteTaskOK ", 200)
}

func (o *DeleteTaskOK) String() string {
	return fmt.Sprintf("[DELETE /task/{id}][%d] deleteTaskOK ", 200)
}

func (o *DeleteTaskOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteTaskServiceUnavailable creates a DeleteTaskServiceUnavailable with default headers values
func NewDeleteTaskServiceUnavailable() *DeleteTaskServiceUnavailable {
	return &DeleteTaskServiceUnavailable{}
}

/*
DeleteTaskServiceUnavailable describes a response with status code 503, with default header values.

apiError
*/
type DeleteTaskServiceUnavailable struct {
	Payload *models.APIError
}

// IsSuccess returns true when this delete task service unavailable response has a 2xx status code
func (o *DeleteTaskServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete task service unavailable response has a 3xx status code
func (o *DeleteTaskServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete task service unavailable response has a 4xx status code
func (o *DeleteTaskServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete task service unavailable response has a 5xx status code
func (o *DeleteTaskServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this delete task service unavailable response a status code equal to that given
func (o *DeleteTaskServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the delete task service unavailable response
func (o *DeleteTaskServiceUnavailable) Code() int {
	return 503
}

func (o *DeleteTaskServiceUnavailable) Error() string {
	return fmt.Sprintf("[DELETE /task/{id}][%d] deleteTaskServiceUnavailable  %+v", 503, o.Payload)
}

func (o *DeleteTaskServiceUnavailable) String() string {
	return fmt.Sprintf("[DELETE /task/{id}][%d] deleteTaskServiceUnavailable  %+v", 503, o.Payload)
}

func (o *DeleteTaskServiceUnavailable) GetPayload() *models.APIError {
	return o.Payload
}

func (o *DeleteTaskServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
