// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ipfs-force-community/brightbird/models"
)

// GetTaskReader is a Reader for the GetTask structure.
type GetTaskReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTaskReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTaskOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 503:
		result := NewGetTaskServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetTaskOK creates a GetTaskOK with default headers values
func NewGetTaskOK() *GetTaskOK {
	return &GetTaskOK{}
}

/*
GetTaskOK describes a response with status code 200, with default header values.

task
*/
type GetTaskOK struct {
	Payload *models.Task
}

// IsSuccess returns true when this get task o k response has a 2xx status code
func (o *GetTaskOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get task o k response has a 3xx status code
func (o *GetTaskOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get task o k response has a 4xx status code
func (o *GetTaskOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get task o k response has a 5xx status code
func (o *GetTaskOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get task o k response a status code equal to that given
func (o *GetTaskOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get task o k response
func (o *GetTaskOK) Code() int {
	return 200
}

func (o *GetTaskOK) Error() string {
	return fmt.Sprintf("[GET /task/{id}][%d] getTaskOK  %+v", 200, o.Payload)
}

func (o *GetTaskOK) String() string {
	return fmt.Sprintf("[GET /task/{id}][%d] getTaskOK  %+v", 200, o.Payload)
}

func (o *GetTaskOK) GetPayload() *models.Task {
	return o.Payload
}

func (o *GetTaskOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Task)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTaskServiceUnavailable creates a GetTaskServiceUnavailable with default headers values
func NewGetTaskServiceUnavailable() *GetTaskServiceUnavailable {
	return &GetTaskServiceUnavailable{}
}

/*
GetTaskServiceUnavailable describes a response with status code 503, with default header values.

apiError
*/
type GetTaskServiceUnavailable struct {
	Payload *models.APIError
}

// IsSuccess returns true when this get task service unavailable response has a 2xx status code
func (o *GetTaskServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get task service unavailable response has a 3xx status code
func (o *GetTaskServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get task service unavailable response has a 4xx status code
func (o *GetTaskServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this get task service unavailable response has a 5xx status code
func (o *GetTaskServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this get task service unavailable response a status code equal to that given
func (o *GetTaskServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the get task service unavailable response
func (o *GetTaskServiceUnavailable) Code() int {
	return 503
}

func (o *GetTaskServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /task/{id}][%d] getTaskServiceUnavailable  %+v", 503, o.Payload)
}

func (o *GetTaskServiceUnavailable) String() string {
	return fmt.Sprintf("[GET /task/{id}][%d] getTaskServiceUnavailable  %+v", 503, o.Payload)
}

func (o *GetTaskServiceUnavailable) GetPayload() *models.APIError {
	return o.Payload
}

func (o *GetTaskServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
