// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ipfs-force-community/brightbird/models"
)

// ListTasksReqReader is a Reader for the ListTasksReq structure.
type ListTasksReqReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListTasksReqReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListTasksReqOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 503:
		result := NewListTasksReqServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListTasksReqOK creates a ListTasksReqOK with default headers values
func NewListTasksReqOK() *ListTasksReqOK {
	return &ListTasksReqOK{}
}

/*
ListTasksReqOK describes a response with status code 200, with default header values.

listTasksResp
*/
type ListTasksReqOK struct {
	Payload *models.ListTasksResp
}

// IsSuccess returns true when this list tasks req o k response has a 2xx status code
func (o *ListTasksReqOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list tasks req o k response has a 3xx status code
func (o *ListTasksReqOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list tasks req o k response has a 4xx status code
func (o *ListTasksReqOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list tasks req o k response has a 5xx status code
func (o *ListTasksReqOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list tasks req o k response a status code equal to that given
func (o *ListTasksReqOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list tasks req o k response
func (o *ListTasksReqOK) Code() int {
	return 200
}

func (o *ListTasksReqOK) Error() string {
	return fmt.Sprintf("[GET /task][%d] listTasksReqOK  %+v", 200, o.Payload)
}

func (o *ListTasksReqOK) String() string {
	return fmt.Sprintf("[GET /task][%d] listTasksReqOK  %+v", 200, o.Payload)
}

func (o *ListTasksReqOK) GetPayload() *models.ListTasksResp {
	return o.Payload
}

func (o *ListTasksReqOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ListTasksResp)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListTasksReqServiceUnavailable creates a ListTasksReqServiceUnavailable with default headers values
func NewListTasksReqServiceUnavailable() *ListTasksReqServiceUnavailable {
	return &ListTasksReqServiceUnavailable{}
}

/*
ListTasksReqServiceUnavailable describes a response with status code 503, with default header values.

apiError
*/
type ListTasksReqServiceUnavailable struct {
	Payload *models.APIError
}

// IsSuccess returns true when this list tasks req service unavailable response has a 2xx status code
func (o *ListTasksReqServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list tasks req service unavailable response has a 3xx status code
func (o *ListTasksReqServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list tasks req service unavailable response has a 4xx status code
func (o *ListTasksReqServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this list tasks req service unavailable response has a 5xx status code
func (o *ListTasksReqServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this list tasks req service unavailable response a status code equal to that given
func (o *ListTasksReqServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the list tasks req service unavailable response
func (o *ListTasksReqServiceUnavailable) Code() int {
	return 503
}

func (o *ListTasksReqServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /task][%d] listTasksReqServiceUnavailable  %+v", 503, o.Payload)
}

func (o *ListTasksReqServiceUnavailable) String() string {
	return fmt.Sprintf("[GET /task][%d] listTasksReqServiceUnavailable  %+v", 503, o.Payload)
}

func (o *ListTasksReqServiceUnavailable) GetPayload() *models.APIError {
	return o.Payload
}

func (o *ListTasksReqServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
