// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPassRateTrendsParams creates a new PassRateTrendsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPassRateTrendsParams() *PassRateTrendsParams {
	return &PassRateTrendsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPassRateTrendsParamsWithTimeout creates a new PassRateTrendsParams object
// with the ability to set a timeout on a request.
func NewPassRateTrendsParamsWithTimeout(timeout time.Duration) *PassRateTrendsParams {
	return &PassRateTrendsParams{
		timeout: timeout,
	}
}

// NewPassRateTrendsParamsWithContext creates a new PassRateTrendsParams object
// with the ability to set a context for a request.
func NewPassRateTrendsParamsWithContext(ctx context.Context) *PassRateTrendsParams {
	return &PassRateTrendsParams{
		Context: ctx,
	}
}

// NewPassRateTrendsParamsWithHTTPClient creates a new PassRateTrendsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPassRateTrendsParamsWithHTTPClient(client *http.Client) *PassRateTrendsParams {
	return &PassRateTrendsParams{
		HTTPClient: client,
	}
}

/*
PassRateTrendsParams contains all the parameters to send to the API endpoint

	for the pass rate trends operation.

	Typically these are written to a http.Request.
*/
type PassRateTrendsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the pass rate trends params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PassRateTrendsParams) WithDefaults() *PassRateTrendsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the pass rate trends params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PassRateTrendsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the pass rate trends params
func (o *PassRateTrendsParams) WithTimeout(timeout time.Duration) *PassRateTrendsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the pass rate trends params
func (o *PassRateTrendsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the pass rate trends params
func (o *PassRateTrendsParams) WithContext(ctx context.Context) *PassRateTrendsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the pass rate trends params
func (o *PassRateTrendsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the pass rate trends params
func (o *PassRateTrendsParams) WithHTTPClient(client *http.Client) *PassRateTrendsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the pass rate trends params
func (o *PassRateTrendsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PassRateTrendsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
