// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ipfs-force-community/brightbird/models"
)

// TodayPassRateRankingReqReader is a Reader for the TodayPassRateRankingReq structure.
type TodayPassRateRankingReqReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TodayPassRateRankingReqReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTodayPassRateRankingReqOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewTodayPassRateRankingReqInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /today-pass-rate-ranking] todayPassRateRankingReq", response, response.Code())
	}
}

// NewTodayPassRateRankingReqOK creates a TodayPassRateRankingReqOK with default headers values
func NewTodayPassRateRankingReqOK() *TodayPassRateRankingReqOK {
	return &TodayPassRateRankingReqOK{}
}

/*
TodayPassRateRankingReqOK describes a response with status code 200, with default header values.

	//todo fix correctstruct
*/
type TodayPassRateRankingReqOK struct {
	Payload models.MyString
}

// IsSuccess returns true when this today pass rate ranking req o k response has a 2xx status code
func (o *TodayPassRateRankingReqOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this today pass rate ranking req o k response has a 3xx status code
func (o *TodayPassRateRankingReqOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this today pass rate ranking req o k response has a 4xx status code
func (o *TodayPassRateRankingReqOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this today pass rate ranking req o k response has a 5xx status code
func (o *TodayPassRateRankingReqOK) IsServerError() bool {
	return false
}

// IsCode returns true when this today pass rate ranking req o k response a status code equal to that given
func (o *TodayPassRateRankingReqOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the today pass rate ranking req o k response
func (o *TodayPassRateRankingReqOK) Code() int {
	return 200
}

func (o *TodayPassRateRankingReqOK) Error() string {
	return fmt.Sprintf("[GET /today-pass-rate-ranking][%d] todayPassRateRankingReqOK  %+v", 200, o.Payload)
}

func (o *TodayPassRateRankingReqOK) String() string {
	return fmt.Sprintf("[GET /today-pass-rate-ranking][%d] todayPassRateRankingReqOK  %+v", 200, o.Payload)
}

func (o *TodayPassRateRankingReqOK) GetPayload() models.MyString {
	return o.Payload
}

func (o *TodayPassRateRankingReqOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTodayPassRateRankingReqInternalServerError creates a TodayPassRateRankingReqInternalServerError with default headers values
func NewTodayPassRateRankingReqInternalServerError() *TodayPassRateRankingReqInternalServerError {
	return &TodayPassRateRankingReqInternalServerError{}
}

/*
TodayPassRateRankingReqInternalServerError describes a response with status code 500, with default header values.

apiError
*/
type TodayPassRateRankingReqInternalServerError struct {
	Payload *models.APIError
}

// IsSuccess returns true when this today pass rate ranking req internal server error response has a 2xx status code
func (o *TodayPassRateRankingReqInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this today pass rate ranking req internal server error response has a 3xx status code
func (o *TodayPassRateRankingReqInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this today pass rate ranking req internal server error response has a 4xx status code
func (o *TodayPassRateRankingReqInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this today pass rate ranking req internal server error response has a 5xx status code
func (o *TodayPassRateRankingReqInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this today pass rate ranking req internal server error response a status code equal to that given
func (o *TodayPassRateRankingReqInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the today pass rate ranking req internal server error response
func (o *TodayPassRateRankingReqInternalServerError) Code() int {
	return 500
}

func (o *TodayPassRateRankingReqInternalServerError) Error() string {
	return fmt.Sprintf("[GET /today-pass-rate-ranking][%d] todayPassRateRankingReqInternalServerError  %+v", 500, o.Payload)
}

func (o *TodayPassRateRankingReqInternalServerError) String() string {
	return fmt.Sprintf("[GET /today-pass-rate-ranking][%d] todayPassRateRankingReqInternalServerError  %+v", 500, o.Payload)
}

func (o *TodayPassRateRankingReqInternalServerError) GetPayload() *models.APIError {
	return o.Payload
}

func (o *TodayPassRateRankingReqInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
