// Code generated by go-swagger; DO NOT EDIT.

package group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hunjixin/brightbird/models"
)

// CountGroupReader is a Reader for the CountGroup structure.
type CountGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CountGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCountGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 503:
		result := NewCountGroupServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCountGroupOK creates a CountGroupOK with default headers values
func NewCountGroupOK() *CountGroupOK {
	return &CountGroupOK{}
}

/*
CountGroupOK describes a response with status code 200, with default header values.

CountGroupOK count group o k
*/
type CountGroupOK struct {
}

// IsSuccess returns true when this count group o k response has a 2xx status code
func (o *CountGroupOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this count group o k response has a 3xx status code
func (o *CountGroupOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this count group o k response has a 4xx status code
func (o *CountGroupOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this count group o k response has a 5xx status code
func (o *CountGroupOK) IsServerError() bool {
	return false
}

// IsCode returns true when this count group o k response a status code equal to that given
func (o *CountGroupOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the count group o k response
func (o *CountGroupOK) Code() int {
	return 200
}

func (o *CountGroupOK) Error() string {
	return fmt.Sprintf("[GET /group/count][%d] countGroupOK ", 200)
}

func (o *CountGroupOK) String() string {
	return fmt.Sprintf("[GET /group/count][%d] countGroupOK ", 200)
}

func (o *CountGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCountGroupServiceUnavailable creates a CountGroupServiceUnavailable with default headers values
func NewCountGroupServiceUnavailable() *CountGroupServiceUnavailable {
	return &CountGroupServiceUnavailable{}
}

/*
CountGroupServiceUnavailable describes a response with status code 503, with default header values.

apiError
*/
type CountGroupServiceUnavailable struct {
	Payload *models.APIError
}

// IsSuccess returns true when this count group service unavailable response has a 2xx status code
func (o *CountGroupServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this count group service unavailable response has a 3xx status code
func (o *CountGroupServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this count group service unavailable response has a 4xx status code
func (o *CountGroupServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this count group service unavailable response has a 5xx status code
func (o *CountGroupServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this count group service unavailable response a status code equal to that given
func (o *CountGroupServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the count group service unavailable response
func (o *CountGroupServiceUnavailable) Code() int {
	return 503
}

func (o *CountGroupServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /group/count][%d] countGroupServiceUnavailable  %+v", 503, o.Payload)
}

func (o *CountGroupServiceUnavailable) String() string {
	return fmt.Sprintf("[GET /group/count][%d] countGroupServiceUnavailable  %+v", 503, o.Payload)
}

func (o *CountGroupServiceUnavailable) GetPayload() *models.APIError {
	return o.Payload
}

func (o *CountGroupServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
