// Code generated by go-swagger; DO NOT EDIT.

package group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetGroupByIDParams creates a new GetGroupByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetGroupByIDParams() *GetGroupByIDParams {
	return &GetGroupByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetGroupByIDParamsWithTimeout creates a new GetGroupByIDParams object
// with the ability to set a timeout on a request.
func NewGetGroupByIDParamsWithTimeout(timeout time.Duration) *GetGroupByIDParams {
	return &GetGroupByIDParams{
		timeout: timeout,
	}
}

// NewGetGroupByIDParamsWithContext creates a new GetGroupByIDParams object
// with the ability to set a context for a request.
func NewGetGroupByIDParamsWithContext(ctx context.Context) *GetGroupByIDParams {
	return &GetGroupByIDParams{
		Context: ctx,
	}
}

// NewGetGroupByIDParamsWithHTTPClient creates a new GetGroupByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetGroupByIDParamsWithHTTPClient(client *http.Client) *GetGroupByIDParams {
	return &GetGroupByIDParams{
		HTTPClient: client,
	}
}

/*
GetGroupByIDParams contains all the parameters to send to the API endpoint

	for the get group by Id operation.

	Typically these are written to a http.Request.
*/
type GetGroupByIDParams struct {

	/* ID.

	   id of group
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get group by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetGroupByIDParams) WithDefaults() *GetGroupByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get group by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetGroupByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get group by Id params
func (o *GetGroupByIDParams) WithTimeout(timeout time.Duration) *GetGroupByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get group by Id params
func (o *GetGroupByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get group by Id params
func (o *GetGroupByIDParams) WithContext(ctx context.Context) *GetGroupByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get group by Id params
func (o *GetGroupByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get group by Id params
func (o *GetGroupByIDParams) WithHTTPClient(client *http.Client) *GetGroupByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get group by Id params
func (o *GetGroupByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get group by Id params
func (o *GetGroupByIDParams) WithID(id string) *GetGroupByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get group by Id params
func (o *GetGroupByIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetGroupByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
