apiVersion: v1
kind: Service
metadata:
  name: sophon-gateway-{{.UniqueId}}-svc
spec:
  clusterIP: None
  selector:
    app: sophon-gateway-{{.UniqueId}}-pod
  ports:
    - protocol: TCP
      port: 45132