apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: damocles-worker-{{.UniqueId}}
spec:
  replicas: 1
  serviceName: damocles-worker-{{.UniqueId}}-svc
  selector:
    matchLabels:
      app: damocles-worker-{{.UniqueId}}-pod
  template:
    metadata:
      labels:
        app: damocles-worker-{{.UniqueId}}-pod
    spec:
      initContainers:
        - name: init-myservice
          image: {{if gt (len .Registry) 0}}{{.Registry}}/{{end}}library/busybox:1.35
          command: ['sh', '-c', "[ -d \"/root/.damocles-worker\" ]||(mkdir -p /root/.damocles-worker && cp /root/config.tmp /root/.damocles-worker/damocles-worker.toml);"]
          volumeMounts:
            - mountPath: /root
              name: damocles-worker-pvc
            - name: sector-worker-cfg
              mountPath: "/root/config.tmp"
              subPath: "damocles-worker.toml"
            - mountPath: /shared-dir
              name: shared-dir-v
              subPath: {{.NameSpace}}
            - mountPath: /shared-dir/{{.UniqueId}}/{{.MinerAddress}}
              name: shared-dir-v
              subPath: {{.NameSpace}}/{{.UniqueId}}/{{.MinerAddress}}
      containers:
        - name: damocles-worker-{{.UniqueId}}
          image: "{{if gt (len .Registry) 0}}{{.Registry}}/{{end}}filvenus/damocles-worker:{{.CodeVersion}}"
          args: ['daemon', '--config', '/root/.damocles-worker/damocles-worker.toml']
          ports:
            - containerPort: 17891
              protocol: TCP
          volumeMounts:
            - mountPath: /root
              name: damocles-worker-pvc
            - name: sector-worker-cfg
              mountPath: "/root/config.tmp"
              subPath: "damocles-worker.toml"
            - mountPath: /shared-dir
              name: shared-dir-v
              subPath: {{.NameSpace}}
      volumes:
        - name: sector-worker-cfg
          configMap:
            name: damocles-worker-cfg-{{.UniqueId}}
            items:
              - key: damocles-worker.toml
                path: damocles-worker.toml
        - name: shared-dir-v
          persistentVolumeClaim:
            claimName: shared-dir
  volumeClaimTemplates:
    - metadata:
        name: damocles-worker-pvc # name+podname
        labels:
          app: damocles-worker-{{.UniqueId}}-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "nfs-client"
        resources:
          requests:
            storage: 10Gi