apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: venus-market-{{.UniqueId}}-deployment
spec:
  replicas: 1
  serviceName: venus-market-{{.UniqueId}}-svc
  selector:
    matchLabels:
      app: venus-market-{{.UniqueId}}-pod
  template:
    metadata:
      labels:
        app: venus-market-{{.UniqueId}}-pod
    spec:
      initContainers:
        - name: init-myservice
          image: {{if gt (len .PrivateRegistry) 0}}{{.PrivateRegistry}}/{{end}}library/busybox:1.35
          command: ['sh', '-c', "mkdir -p /root/.venusmarket; cp /root/config.tmp /root/.venusmarket/config.toml"]
          volumeMounts:
            - mountPath: /root
              name: venus-market-pvc
            - name: marketcfg
              mountPath: "/root/config.tmp"
              subPath: "config.toml"
            - mountPath: /shared-dir
              name: shared-dir-v
              subPath: {{.NameSpace}}
      initContainers:
        - name: create-piece-dir
          image: busybox:1.28
          command: [ 'sh', '-c', "mkdir -p /shared-dir/m-piece/piece-{{.UniqueId}}" ]
          volumeMounts:
            - mountPath: /shared-dir
              name: shared-dir-v
              subPath: {{.NameSpace}}
      containers:
        - name: venus-market-{{.UniqueId}}
          image: "{{if gt (len .PrivateRegistry) 0}}{{.PrivateRegistry}}/{{end}}filvenus/venus-market:{{.CodeVersion}}"
          args: ["run"]
          ports:
            - containerPort: 41235
              protocol: TCP
            - containerPort: 58418
              protocol: TCP
          volumeMounts:
            - mountPath: /root
              name: venus-market-pvc
            - name: marketcfg
              mountPath: "/root/config.tmp"
              subPath: "config.toml"
            - mountPath: /shared-dir
              name: shared-dir-v
              subPath: {{.NameSpace}}
      volumes:
        - name: marketcfg
          configMap:
            name: venus-market-cfg-{{.UniqueId}}
            items:
              - key: config.toml
                path: config.toml
        - name: shared-dir-v
          persistentVolumeClaim:
            claimName: shared-dir
  volumeClaimTemplates:
    - metadata:
        name: venus-market-pvc # name+podname
        labels:
          app: venus-market-{{.UniqueId}}-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "nfs-client"
        resources:
          requests:
            storage: 1Gi