apiVersion: v1
kind: Service
metadata:
  name: venus-chain-co-{{.UniqueId}}-svc
spec:
  clusterIP: None
  selector:
    app: venus-chain-co-{{.UniqueId}}-pod
  ports:
    - protocol: TCP
      port: 1234