apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: venus-chain-co-{{.UniqueId}}
spec:
  replicas: {{.Replicas}}
  serviceName: venus-chain-co-{{.UniqueId}}-svc
  selector:
    matchLabels:
      app: venus-chain-co-{{.UniqueId}}-pod
  template:
    metadata:
      labels:
        app: venus-chain-co-{{.UniqueId}}-pod
    spec:
      containers:
        - name: venus-chain-co-{{.UniqueId}}
          image: "{{if gt (len .PrivateRegistry) 0}}{{.PrivateRegistry}}/{{end}}filvenus/chain-co:{{.CodeVersion}}"
          args: [run, {{range $i, $a := .Nodes}} {{$a}} {{end}}]
          ports:
            - containerPort: 1234
              protocol: TCP
          volumeMounts:
            - mountPath: /root
              name:  venus-chain-co
  volumeClaimTemplates:
    - metadata:
        name: venus-chain-co-pvc # name+podname
        labels:
          app: venus-chain-co-{{.UniqueId}}-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "nfs-client"
        resources:
          requests:
            storage: 100M