PluginStore = "./plugins"
BootstrapPeers = ["/ip4/192.168.200.24/tcp/33273/p2p/12D3KooWLGdpt2A2WJvMpBVYn3pazrn7TFp1QRnGrt8KZUmFGYUL"]
MongoUrl = 'mongodb://192.168.200.103:27017'
DbName = 'lidb'
PrivateRegistry = '192.168.200.175'
Mysql = "root:Aa123456@(192.168.200.175:3306)/%s?parseTime=true&loc=Local&charset=utf8mb4&collation=utf8mb4_unicode_ci&readTimeout=10s&writeTimeout=10s"