// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hunjixin/brightbird/models"
)

// CountTestFlowsInGroupReader is a Reader for the CountTestFlowsInGroup structure.
type CountTestFlowsInGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CountTestFlowsInGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCountTestFlowsInGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 503:
		result := NewCountTestFlowsInGroupServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCountTestFlowsInGroupOK creates a CountTestFlowsInGroupOK with default headers values
func NewCountTestFlowsInGroupOK() *CountTestFlowsInGroupOK {
	return &CountTestFlowsInGroupOK{}
}

/*
CountTestFlowsInGroupOK describes a response with status code 200, with default header values.

CountTestFlowsInGroupOK count test flows in group o k
*/
type CountTestFlowsInGroupOK struct {
}

// IsSuccess returns true when this count test flows in group o k response has a 2xx status code
func (o *CountTestFlowsInGroupOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this count test flows in group o k response has a 3xx status code
func (o *CountTestFlowsInGroupOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this count test flows in group o k response has a 4xx status code
func (o *CountTestFlowsInGroupOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this count test flows in group o k response has a 5xx status code
func (o *CountTestFlowsInGroupOK) IsServerError() bool {
	return false
}

// IsCode returns true when this count test flows in group o k response a status code equal to that given
func (o *CountTestFlowsInGroupOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the count test flows in group o k response
func (o *CountTestFlowsInGroupOK) Code() int {
	return 200
}

func (o *CountTestFlowsInGroupOK) Error() string {
	return fmt.Sprintf("[GET /testflow/count/][%d] countTestFlowsInGroupOK ", 200)
}

func (o *CountTestFlowsInGroupOK) String() string {
	return fmt.Sprintf("[GET /testflow/count/][%d] countTestFlowsInGroupOK ", 200)
}

func (o *CountTestFlowsInGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCountTestFlowsInGroupServiceUnavailable creates a CountTestFlowsInGroupServiceUnavailable with default headers values
func NewCountTestFlowsInGroupServiceUnavailable() *CountTestFlowsInGroupServiceUnavailable {
	return &CountTestFlowsInGroupServiceUnavailable{}
}

/*
CountTestFlowsInGroupServiceUnavailable describes a response with status code 503, with default header values.

apiError
*/
type CountTestFlowsInGroupServiceUnavailable struct {
	Payload *models.APIError
}

// IsSuccess returns true when this count test flows in group service unavailable response has a 2xx status code
func (o *CountTestFlowsInGroupServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this count test flows in group service unavailable response has a 3xx status code
func (o *CountTestFlowsInGroupServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this count test flows in group service unavailable response has a 4xx status code
func (o *CountTestFlowsInGroupServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this count test flows in group service unavailable response has a 5xx status code
func (o *CountTestFlowsInGroupServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this count test flows in group service unavailable response a status code equal to that given
func (o *CountTestFlowsInGroupServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the count test flows in group service unavailable response
func (o *CountTestFlowsInGroupServiceUnavailable) Code() int {
	return 503
}

func (o *CountTestFlowsInGroupServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /testflow/count/][%d] countTestFlowsInGroupServiceUnavailable  %+v", 503, o.Payload)
}

func (o *CountTestFlowsInGroupServiceUnavailable) String() string {
	return fmt.Sprintf("[GET /testflow/count/][%d] countTestFlowsInGroupServiceUnavailable  %+v", 503, o.Payload)
}

func (o *CountTestFlowsInGroupServiceUnavailable) GetPayload() *models.APIError {
	return o.Payload
}

func (o *CountTestFlowsInGroupServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
