// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteTestFlowParams creates a new DeleteTestFlowParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteTestFlowParams() *DeleteTestFlowParams {
	return &DeleteTestFlowParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteTestFlowParamsWithTimeout creates a new DeleteTestFlowParams object
// with the ability to set a timeout on a request.
func NewDeleteTestFlowParamsWithTimeout(timeout time.Duration) *DeleteTestFlowParams {
	return &DeleteTestFlowParams{
		timeout: timeout,
	}
}

// NewDeleteTestFlowParamsWithContext creates a new DeleteTestFlowParams object
// with the ability to set a context for a request.
func NewDeleteTestFlowParamsWithContext(ctx context.Context) *DeleteTestFlowParams {
	return &DeleteTestFlowParams{
		Context: ctx,
	}
}

// NewDeleteTestFlowParamsWithHTTPClient creates a new DeleteTestFlowParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteTestFlowParamsWithHTTPClient(client *http.Client) *DeleteTestFlowParams {
	return &DeleteTestFlowParams{
		HTTPClient: client,
	}
}

/*
DeleteTestFlowParams contains all the parameters to send to the API endpoint

	for the delete test flow operation.

	Typically these are written to a http.Request.
*/
type DeleteTestFlowParams struct {

	/* ID.

	   id of test flow
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete test flow params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteTestFlowParams) WithDefaults() *DeleteTestFlowParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete test flow params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteTestFlowParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete test flow params
func (o *DeleteTestFlowParams) WithTimeout(timeout time.Duration) *DeleteTestFlowParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete test flow params
func (o *DeleteTestFlowParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete test flow params
func (o *DeleteTestFlowParams) WithContext(ctx context.Context) *DeleteTestFlowParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete test flow params
func (o *DeleteTestFlowParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete test flow params
func (o *DeleteTestFlowParams) WithHTTPClient(client *http.Client) *DeleteTestFlowParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete test flow params
func (o *DeleteTestFlowParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete test flow params
func (o *DeleteTestFlowParams) WithID(id string) *DeleteTestFlowParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete test flow params
func (o *DeleteTestFlowParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteTestFlowParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
