// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hunjixin/brightbird/models"
)

// DeletePluginReader is a Reader for the DeletePlugin structure.
type DeletePluginReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeletePluginReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeletePluginOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 503:
		result := NewDeletePluginServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeletePluginOK creates a DeletePluginOK with default headers values
func NewDeletePluginOK() *DeletePluginOK {
	return &DeletePluginOK{}
}

/*
DeletePluginOK describes a response with status code 200, with default header values.

DeletePluginOK delete plugin o k
*/
type DeletePluginOK struct {
}

// IsSuccess returns true when this delete plugin o k response has a 2xx status code
func (o *DeletePluginOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete plugin o k response has a 3xx status code
func (o *DeletePluginOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete plugin o k response has a 4xx status code
func (o *DeletePluginOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete plugin o k response has a 5xx status code
func (o *DeletePluginOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete plugin o k response a status code equal to that given
func (o *DeletePluginOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete plugin o k response
func (o *DeletePluginOK) Code() int {
	return 200
}

func (o *DeletePluginOK) Error() string {
	return fmt.Sprintf("[DELETE /plugin][%d] deletePluginOK ", 200)
}

func (o *DeletePluginOK) String() string {
	return fmt.Sprintf("[DELETE /plugin][%d] deletePluginOK ", 200)
}

func (o *DeletePluginOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeletePluginServiceUnavailable creates a DeletePluginServiceUnavailable with default headers values
func NewDeletePluginServiceUnavailable() *DeletePluginServiceUnavailable {
	return &DeletePluginServiceUnavailable{}
}

/*
DeletePluginServiceUnavailable describes a response with status code 503, with default header values.

apiError
*/
type DeletePluginServiceUnavailable struct {
	Payload *models.APIError
}

// IsSuccess returns true when this delete plugin service unavailable response has a 2xx status code
func (o *DeletePluginServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete plugin service unavailable response has a 3xx status code
func (o *DeletePluginServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete plugin service unavailable response has a 4xx status code
func (o *DeletePluginServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete plugin service unavailable response has a 5xx status code
func (o *DeletePluginServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this delete plugin service unavailable response a status code equal to that given
func (o *DeletePluginServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the delete plugin service unavailable response
func (o *DeletePluginServiceUnavailable) Code() int {
	return 503
}

func (o *DeletePluginServiceUnavailable) Error() string {
	return fmt.Sprintf("[DELETE /plugin][%d] deletePluginServiceUnavailable  %+v", 503, o.Payload)
}

func (o *DeletePluginServiceUnavailable) String() string {
	return fmt.Sprintf("[DELETE /plugin][%d] deletePluginServiceUnavailable  %+v", 503, o.Payload)
}

func (o *DeletePluginServiceUnavailable) GetPayload() *models.APIError {
	return o.Payload
}

func (o *DeletePluginServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
