// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTestFlowParams creates a new GetTestFlowParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetTestFlowParams() *GetTestFlowParams {
	return &GetTestFlowParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetTestFlowParamsWithTimeout creates a new GetTestFlowParams object
// with the ability to set a timeout on a request.
func NewGetTestFlowParamsWithTimeout(timeout time.Duration) *GetTestFlowParams {
	return &GetTestFlowParams{
		timeout: timeout,
	}
}

// NewGetTestFlowParamsWithContext creates a new GetTestFlowParams object
// with the ability to set a context for a request.
func NewGetTestFlowParamsWithContext(ctx context.Context) *GetTestFlowParams {
	return &GetTestFlowParams{
		Context: ctx,
	}
}

// NewGetTestFlowParamsWithHTTPClient creates a new GetTestFlowParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetTestFlowParamsWithHTTPClient(client *http.Client) *GetTestFlowParams {
	return &GetTestFlowParams{
		HTTPClient: client,
	}
}

/*
GetTestFlowParams contains all the parameters to send to the API endpoint

	for the get test flow operation.

	Typically these are written to a http.Request.
*/
type GetTestFlowParams struct {

	/* ID.

	   id of test flow
	*/
	ID string

	/* Name.

	   name of test flow
	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get test flow params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTestFlowParams) WithDefaults() *GetTestFlowParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get test flow params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTestFlowParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get test flow params
func (o *GetTestFlowParams) WithTimeout(timeout time.Duration) *GetTestFlowParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get test flow params
func (o *GetTestFlowParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get test flow params
func (o *GetTestFlowParams) WithContext(ctx context.Context) *GetTestFlowParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get test flow params
func (o *GetTestFlowParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get test flow params
func (o *GetTestFlowParams) WithHTTPClient(client *http.Client) *GetTestFlowParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get test flow params
func (o *GetTestFlowParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get test flow params
func (o *GetTestFlowParams) WithID(id string) *GetTestFlowParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get test flow params
func (o *GetTestFlowParams) SetID(id string) {
	o.ID = id
}

// WithName adds the name to the get test flow params
func (o *GetTestFlowParams) WithName(name string) *GetTestFlowParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get test flow params
func (o *GetTestFlowParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetTestFlowParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param id
	qrID := o.ID
	qID := qrID
	if qID != "" {

		if err := r.SetQueryParam("id", qID); err != nil {
			return err
		}
	}

	// query param name
	qrName := o.Name
	qName := qrName
	if qName != "" {

		if err := r.SetQueryParam("name", qName); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
