// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hunjixin/brightbird/models"
)

// GetPluginManifestReader is a Reader for the GetPluginManifest structure.
type GetPluginManifestReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPluginManifestReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPluginManifestOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 503:
		result := NewGetPluginManifestServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetPluginManifestOK creates a GetPluginManifestOK with default headers values
func NewGetPluginManifestOK() *GetPluginManifestOK {
	return &GetPluginManifestOK{}
}

/*
GetPluginManifestOK describes a response with status code 200, with default header values.

pluginInfo
*/
type GetPluginManifestOK struct {
	Payload []*models.PluginInfo
}

// IsSuccess returns true when this get plugin manifest o k response has a 2xx status code
func (o *GetPluginManifestOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get plugin manifest o k response has a 3xx status code
func (o *GetPluginManifestOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get plugin manifest o k response has a 4xx status code
func (o *GetPluginManifestOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get plugin manifest o k response has a 5xx status code
func (o *GetPluginManifestOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get plugin manifest o k response a status code equal to that given
func (o *GetPluginManifestOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get plugin manifest o k response
func (o *GetPluginManifestOK) Code() int {
	return 200
}

func (o *GetPluginManifestOK) Error() string {
	return fmt.Sprintf("[GET /plugin/mainfest][%d] getPluginManifestOK  %+v", 200, o.Payload)
}

func (o *GetPluginManifestOK) String() string {
	return fmt.Sprintf("[GET /plugin/mainfest][%d] getPluginManifestOK  %+v", 200, o.Payload)
}

func (o *GetPluginManifestOK) GetPayload() []*models.PluginInfo {
	return o.Payload
}

func (o *GetPluginManifestOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPluginManifestServiceUnavailable creates a GetPluginManifestServiceUnavailable with default headers values
func NewGetPluginManifestServiceUnavailable() *GetPluginManifestServiceUnavailable {
	return &GetPluginManifestServiceUnavailable{}
}

/*
GetPluginManifestServiceUnavailable describes a response with status code 503, with default header values.

apiError
*/
type GetPluginManifestServiceUnavailable struct {
	Payload *models.APIError
}

// IsSuccess returns true when this get plugin manifest service unavailable response has a 2xx status code
func (o *GetPluginManifestServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get plugin manifest service unavailable response has a 3xx status code
func (o *GetPluginManifestServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get plugin manifest service unavailable response has a 4xx status code
func (o *GetPluginManifestServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this get plugin manifest service unavailable response has a 5xx status code
func (o *GetPluginManifestServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this get plugin manifest service unavailable response a status code equal to that given
func (o *GetPluginManifestServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the get plugin manifest service unavailable response
func (o *GetPluginManifestServiceUnavailable) Code() int {
	return 503
}

func (o *GetPluginManifestServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /plugin/mainfest][%d] getPluginManifestServiceUnavailable  %+v", 503, o.Payload)
}

func (o *GetPluginManifestServiceUnavailable) String() string {
	return fmt.Sprintf("[GET /plugin/mainfest][%d] getPluginManifestServiceUnavailable  %+v", 503, o.Payload)
}

func (o *GetPluginManifestServiceUnavailable) GetPayload() *models.APIError {
	return o.Payload
}

func (o *GetPluginManifestServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
