// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListExecPluginParams creates a new ListExecPluginParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListExecPluginParams() *ListExecPluginParams {
	return &ListExecPluginParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListExecPluginParamsWithTimeout creates a new ListExecPluginParams object
// with the ability to set a timeout on a request.
func NewListExecPluginParamsWithTimeout(timeout time.Duration) *ListExecPluginParams {
	return &ListExecPluginParams{
		timeout: timeout,
	}
}

// NewListExecPluginParamsWithContext creates a new ListExecPluginParams object
// with the ability to set a context for a request.
func NewListExecPluginParamsWithContext(ctx context.Context) *ListExecPluginParams {
	return &ListExecPluginParams{
		Context: ctx,
	}
}

// NewListExecPluginParamsWithHTTPClient creates a new ListExecPluginParams object
// with the ability to set a custom HTTPClient for a request.
func NewListExecPluginParamsWithHTTPClient(client *http.Client) *ListExecPluginParams {
	return &ListExecPluginParams{
		HTTPClient: client,
	}
}

/*
ListExecPluginParams contains all the parameters to send to the API endpoint

	for the list exec plugin operation.

	Typically these are written to a http.Request.
*/
type ListExecPluginParams struct {

	/* Name.

	   name of plugin
	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list exec plugin params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListExecPluginParams) WithDefaults() *ListExecPluginParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list exec plugin params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListExecPluginParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list exec plugin params
func (o *ListExecPluginParams) WithTimeout(timeout time.Duration) *ListExecPluginParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list exec plugin params
func (o *ListExecPluginParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list exec plugin params
func (o *ListExecPluginParams) WithContext(ctx context.Context) *ListExecPluginParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list exec plugin params
func (o *ListExecPluginParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list exec plugin params
func (o *ListExecPluginParams) WithHTTPClient(client *http.Client) *ListExecPluginParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list exec plugin params
func (o *ListExecPluginParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the list exec plugin params
func (o *ListExecPluginParams) WithName(name string) *ListExecPluginParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the list exec plugin params
func (o *ListExecPluginParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *ListExecPluginParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param name
	qrName := o.Name
	qName := qrName
	if qName != "" {

		if err := r.SetQueryParam("name", qName); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
