// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListPodsInTestParams creates a new ListPodsInTestParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListPodsInTestParams() *ListPodsInTestParams {
	return &ListPodsInTestParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListPodsInTestParamsWithTimeout creates a new ListPodsInTestParams object
// with the ability to set a timeout on a request.
func NewListPodsInTestParamsWithTimeout(timeout time.Duration) *ListPodsInTestParams {
	return &ListPodsInTestParams{
		timeout: timeout,
	}
}

// NewListPodsInTestParamsWithContext creates a new ListPodsInTestParams object
// with the ability to set a context for a request.
func NewListPodsInTestParamsWithContext(ctx context.Context) *ListPodsInTestParams {
	return &ListPodsInTestParams{
		Context: ctx,
	}
}

// NewListPodsInTestParamsWithHTTPClient creates a new ListPodsInTestParams object
// with the ability to set a custom HTTPClient for a request.
func NewListPodsInTestParamsWithHTTPClient(client *http.Client) *ListPodsInTestParams {
	return &ListPodsInTestParams{
		HTTPClient: client,
	}
}

/*
ListPodsInTestParams contains all the parameters to send to the API endpoint

	for the list pods in test operation.

	Typically these are written to a http.Request.
*/
type ListPodsInTestParams struct {

	/* Testid.

	   test id
	*/
	Testid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list pods in test params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListPodsInTestParams) WithDefaults() *ListPodsInTestParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list pods in test params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListPodsInTestParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list pods in test params
func (o *ListPodsInTestParams) WithTimeout(timeout time.Duration) *ListPodsInTestParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list pods in test params
func (o *ListPodsInTestParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list pods in test params
func (o *ListPodsInTestParams) WithContext(ctx context.Context) *ListPodsInTestParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list pods in test params
func (o *ListPodsInTestParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list pods in test params
func (o *ListPodsInTestParams) WithHTTPClient(client *http.Client) *ListPodsInTestParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list pods in test params
func (o *ListPodsInTestParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTestid adds the testid to the list pods in test params
func (o *ListPodsInTestParams) WithTestid(testid string) *ListPodsInTestParams {
	o.SetTestid(testid)
	return o
}

// SetTestid adds the testid to the list pods in test params
func (o *ListPodsInTestParams) SetTestid(testid string) {
	o.Testid = testid
}

// WriteToRequest writes these params to a swagger request
func (o *ListPodsInTestParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param testid
	if err := r.SetPathParam("testid", o.Testid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
