// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hunjixin/brightbird/models"
)

// ListGroupReader is a Reader for the ListGroup structure.
type ListGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 503:
		result := NewListGroupServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListGroupOK creates a ListGroupOK with default headers values
func NewListGroupOK() *ListGroupOK {
	return &ListGroupOK{}
}

/*
ListGroupOK describes a response with status code 200, with default header values.

listGroupResp
*/
type ListGroupOK struct {
	Payload models.ListGroupResp
}

// IsSuccess returns true when this list group o k response has a 2xx status code
func (o *ListGroupOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list group o k response has a 3xx status code
func (o *ListGroupOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list group o k response has a 4xx status code
func (o *ListGroupOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list group o k response has a 5xx status code
func (o *ListGroupOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list group o k response a status code equal to that given
func (o *ListGroupOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list group o k response
func (o *ListGroupOK) Code() int {
	return 200
}

func (o *ListGroupOK) Error() string {
	return fmt.Sprintf("[GET /group][%d] listGroupOK  %+v", 200, o.Payload)
}

func (o *ListGroupOK) String() string {
	return fmt.Sprintf("[GET /group][%d] listGroupOK  %+v", 200, o.Payload)
}

func (o *ListGroupOK) GetPayload() models.ListGroupResp {
	return o.Payload
}

func (o *ListGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListGroupServiceUnavailable creates a ListGroupServiceUnavailable with default headers values
func NewListGroupServiceUnavailable() *ListGroupServiceUnavailable {
	return &ListGroupServiceUnavailable{}
}

/*
ListGroupServiceUnavailable describes a response with status code 503, with default header values.

apiError
*/
type ListGroupServiceUnavailable struct {
	Payload *models.APIError
}

// IsSuccess returns true when this list group service unavailable response has a 2xx status code
func (o *ListGroupServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list group service unavailable response has a 3xx status code
func (o *ListGroupServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list group service unavailable response has a 4xx status code
func (o *ListGroupServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this list group service unavailable response has a 5xx status code
func (o *ListGroupServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this list group service unavailable response a status code equal to that given
func (o *ListGroupServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the list group service unavailable response
func (o *ListGroupServiceUnavailable) Code() int {
	return 503
}

func (o *ListGroupServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /group][%d] listGroupServiceUnavailable  %+v", 503, o.Payload)
}

func (o *ListGroupServiceUnavailable) String() string {
	return fmt.Sprintf("[GET /group][%d] listGroupServiceUnavailable  %+v", 503, o.Payload)
}

func (o *ListGroupServiceUnavailable) GetPayload() *models.APIError {
	return o.Payload
}

func (o *ListGroupServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
