// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/hunjixin/brightbird/models"
)

// NewSaveJobParams creates a new SaveJobParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSaveJobParams() *SaveJobParams {
	return &SaveJobParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSaveJobParamsWithTimeout creates a new SaveJobParams object
// with the ability to set a timeout on a request.
func NewSaveJobParamsWithTimeout(timeout time.Duration) *SaveJobParams {
	return &SaveJobParams{
		timeout: timeout,
	}
}

// NewSaveJobParamsWithContext creates a new SaveJobParams object
// with the ability to set a context for a request.
func NewSaveJobParamsWithContext(ctx context.Context) *SaveJobParams {
	return &SaveJobParams{
		Context: ctx,
	}
}

// NewSaveJobParamsWithHTTPClient creates a new SaveJobParams object
// with the ability to set a custom HTTPClient for a request.
func NewSaveJobParamsWithHTTPClient(client *http.Client) *SaveJobParams {
	return &SaveJobParams{
		HTTPClient: client,
	}
}

/*
SaveJobParams contains all the parameters to send to the API endpoint

	for the save job operation.

	Typically these are written to a http.Request.
*/
type SaveJobParams struct {

	/* Job.

	   job json
	*/
	Job *models.Job

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the save job params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SaveJobParams) WithDefaults() *SaveJobParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the save job params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SaveJobParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the save job params
func (o *SaveJobParams) WithTimeout(timeout time.Duration) *SaveJobParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the save job params
func (o *SaveJobParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the save job params
func (o *SaveJobParams) WithContext(ctx context.Context) *SaveJobParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the save job params
func (o *SaveJobParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the save job params
func (o *SaveJobParams) WithHTTPClient(client *http.Client) *SaveJobParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the save job params
func (o *SaveJobParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithJob adds the job to the save job params
func (o *SaveJobParams) WithJob(job *models.Job) *SaveJobParams {
	o.SetJob(job)
	return o
}

// SetJob adds the job to the save job params
func (o *SaveJobParams) SetJob(job *models.Job) {
	o.Job = job
}

// WriteToRequest writes these params to a swagger request
func (o *SaveJobParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Job != nil {
		if err := r.SetBodyParam(o.Job); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
