// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hunjixin/brightbird/models"
)

// UploadPluginReader is a Reader for the UploadPlugin structure.
type UploadPluginReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UploadPluginReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUploadPluginOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 503:
		result := NewUploadPluginServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUploadPluginOK creates a UploadPluginOK with default headers values
func NewUploadPluginOK() *UploadPluginOK {
	return &UploadPluginOK{}
}

/*
UploadPluginOK describes a response with status code 200, with default header values.

pluginOut
*/
type UploadPluginOK struct {
	Payload []*models.PluginOut
}

// IsSuccess returns true when this upload plugin o k response has a 2xx status code
func (o *UploadPluginOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this upload plugin o k response has a 3xx status code
func (o *UploadPluginOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this upload plugin o k response has a 4xx status code
func (o *UploadPluginOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this upload plugin o k response has a 5xx status code
func (o *UploadPluginOK) IsServerError() bool {
	return false
}

// IsCode returns true when this upload plugin o k response a status code equal to that given
func (o *UploadPluginOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the upload plugin o k response
func (o *UploadPluginOK) Code() int {
	return 200
}

func (o *UploadPluginOK) Error() string {
	return fmt.Sprintf("[GET /plugin/upload][%d] uploadPluginOK  %+v", 200, o.Payload)
}

func (o *UploadPluginOK) String() string {
	return fmt.Sprintf("[GET /plugin/upload][%d] uploadPluginOK  %+v", 200, o.Payload)
}

func (o *UploadPluginOK) GetPayload() []*models.PluginOut {
	return o.Payload
}

func (o *UploadPluginOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUploadPluginServiceUnavailable creates a UploadPluginServiceUnavailable with default headers values
func NewUploadPluginServiceUnavailable() *UploadPluginServiceUnavailable {
	return &UploadPluginServiceUnavailable{}
}

/*
UploadPluginServiceUnavailable describes a response with status code 503, with default header values.

apiError
*/
type UploadPluginServiceUnavailable struct {
	Payload *models.APIError
}

// IsSuccess returns true when this upload plugin service unavailable response has a 2xx status code
func (o *UploadPluginServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this upload plugin service unavailable response has a 3xx status code
func (o *UploadPluginServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this upload plugin service unavailable response has a 4xx status code
func (o *UploadPluginServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this upload plugin service unavailable response has a 5xx status code
func (o *UploadPluginServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this upload plugin service unavailable response a status code equal to that given
func (o *UploadPluginServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the upload plugin service unavailable response
func (o *UploadPluginServiceUnavailable) Code() int {
	return 503
}

func (o *UploadPluginServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /plugin/upload][%d] uploadPluginServiceUnavailable  %+v", 503, o.Payload)
}

func (o *UploadPluginServiceUnavailable) String() string {
	return fmt.Sprintf("[GET /plugin/upload][%d] uploadPluginServiceUnavailable  %+v", 503, o.Payload)
}

func (o *UploadPluginServiceUnavailable) GetPayload() *models.APIError {
	return o.Payload
}

func (o *UploadPluginServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
