apiVersion: v1
data:
  config.toml: |
        Port = "8989"
        Secret = "1299c3162a7c51ce11f473c1cc011c7dd263a2a7a69549abb42ded69d7607f29"
        ReadTimeout = 60000000000
        WriteTimeout = 60000000000
        IdleTimeout = 60000000000

        [Log]
        LogLevel = "trace"
        Type = 0
        HookSwitch = false

        [DB]
        Type = "{{if gt (len .MysqlDSN) 0}}mysql{{else}}badger{{end}}"
        DSN = "{{.MysqlDSN}}"
        MaxOpenConns = 0
        MaxIdleConns = 0
        MaxLifeTime = 0
        MaxIdleTime = 0
        Debug = false

        [Trace]
        JaegerTracingEnabled = false
        ProbabilitySampler = 1.0
        JaegerEndpoint = "localhost:6831"
        ServerName = "venus-auth"
kind: ConfigMap
metadata:
  name: venus-auth-ha-{{.UniqueId}}