apiVersion: v1
kind: ConfigMap
metadata:
  name: damocles-worker-gpu-cfg-{{.UniqueId}}
data:
  sectorstore.json: |
    {
    	"ID": "5e211009-219b-4d52-b1c1-9c5ef4ac7c22",
    	"Name": "attachedtest-t023456",
    	"Path": "/storage-nfs-4/baiyu/t023456",
    	"Meta": null,
    	"Strict": true,
    	"ReadOnly": false,
    	"Weight": 1,
    	"AllowMiners": [23456],
    	"DenyMiners": [],
    	"Plugin": "",
    	"PluginName": ""
    }
  damocles-worker.toml: |
    [worker]
    name = "k8s-node4"
    rpc_server.host = "0.0.0.0"
    rpc_server.port = 17890
    #ScanPersistStores = ["/storage-nfs-4/baiyu/t023456"]
    ScanPersistStores = ["/storage"]

    [sector_manager]
    rpc_client.addr = "{{.DamoclesManagerUrl}}"
    rpc_client.headers = { User-Agent = "jsonrpc-core-client" }
    piece_token = "{{.UserToken}}"
    [sealing]
    allowed_miners = [23456]
    allowed_sizes = ["32GiB"]
    enable_deals = true
    disable_cc = false
    max_deals = 6
    min_deal_space = "1KiB"
    max_retries = 3
    
    [[sealing_thread]]
    location = "/mnt/mount/nvme/localdir1"
    [[sealing_thread]]
    location = "/mnt/mount/nvme/localdir2"
    [[sealing_thread]]
    location = "/mnt/mount/nvme/localdir3"
    [[sealing_thread]]
    location = "/mnt/mount/nvme/localdir4"
    [[sealing_thread]]
    location = "/mnt/mount/nvme/localdir5"
    [[sealing_thread]]
    location = "/mnt/mount/nvme/localdir6"
    [[sealing_thread]]
    location = "/mnt/mount/nvme/localdir7"
    [[sealing_thread]]
    location = "/mnt/mount/nvme/localdir8"
    [[sealing_thread]]
    location = "/mnt/mount/nvme/rebuild1"
    plan = "rebuild"
    
    [processors.limitation.concurrent]
    add_pieces = 2
    tree_d = 2
    pc1 = 4
    pc2 = 1
    c2 = 1
    
    #window_post = 1
    #snap_encode = 1
    #snap_prove = 1
    
    #多机wdpost用worker去做
    #[[processors.window_post]]
    #bin="/root/baiyu/damocles/dist/bin/force-ext-processors"
    #args = ["processor", "window_post"]
    #envs = { BELLMAN_GPU_INDEXS="0", CUDA_VISIBLE_DEVICES="0"}
    #concurrent = 1
    
    [processors.static_tree_d]
    32GiB = "/var/tmp/filecoin-proof-parameters/tree_d_all_zero_34359738368"
    
    #私有算法跑p1
    [[processors.pc1]]
    bin="/cmd/force-ext-processors"
    args = ["processor", "pc1", "--huge_mem_path_32g", "/mnt/huge", "--huge_mem_page_count_32g", "4"]
    numa_preferred = 0
    envs = { FORCE_SECTOR_SIZE="34359738368", FIL_PROOFS_HUGEPAGE_START_INDEX="0", FIL_PROOFS_CORE_START_INDEX="0", FIL_PROOFS_USE_MULTICORE_SDR="1", FIL_PROOFS_MULTICORE_SDR_PRODUCERS="1", FORCE_HUGE_PAGE="1" }
    concurrent = 2
    
    [[processors.pc1]]
    bin="/cmd/force-ext-processors"
    args = ["processor", "pc1", "--huge_mem_path_32g", "/mnt/huge", "--huge_mem_page_count_32g", "4"]
    numa_preferred = 1
    envs = {FORCE_SECTOR_SIZE="34359738368", FIL_PROOFS_HUGEPAGE_START_INDEX="4", FIL_PROOFS_CORE_START_INDEX="24", FIL_PROOFS_USE_MULTICORE_SDR="1", FIL_PROOFS_MULTICORE_SDR_PRODUCERS="1", FORCE_HUGE_PAGE="1" }
    concurrent = 2

    #私有算法跑p2
    [[processors.pc2]]
    bin="/cmd/force-ext-processors"
    concurrent = 1
    envs = { FIL_PROOFS_USE_GPU_COLUMN_BUILDER="1", FIL_PROOFS_USE_GPU_TREE_BUILDER="1", CUDA_VISIBLE_DEVICES="0" }
    
    #私有算法跑c2
    [[processors.c2]]
    bin="/cmd/force-ext-processors"
    args = ["processor", "c2", "--sector_size", "32GiB"]
    concurrent = 1
    envs = { BELLMAN_LOAD_SHM="1", BELLMAN_USE_MAP_BUFFER="1", BELLMAN_CIRCUIT_N="1", BELLMAN_PROOF_N="1", CUDA_VISIBLE_DEVICES="1",BELLMAN_CUSTOM_GPU="NVIDIA GeForce RTX 2080 Ti:4352"}
    
    #c2外包
    #[[processors.c2]]
    #bin="/cluster_c2_plugin"
    #args = ["run", "--gpuproxy-url", "http://192.168.200.18:18888","--log-level", "trace"]

    [[processors.tree_d]]
    cgroup.cpuset = "15-23"
    concurrent = 1

    #[[processors.snap_encode]]
    #cgroup.cpuset = "39-41"
    #concurrent = 1
    #envs = { FIL_PROOFS_USE_GPU_COLUMN_BUILDER = "1", FIL_PROOFS_USE_GPU_TREE_BUILDER = "1", CUDA_VISIBLE_DEVICES = "0" }
    
    #[[processors.snap_prove]]
    #cgroup.cpuset = "42-47"
    #concurrent = 1
    #envs = { CUDA_VISIBLE_DEVICES = "0" }