apiVersion: v1
kind: Service
metadata:
  name: damocles-worker-gpu-{{.UniqueId}}-svc
spec:
  clusterIP: None
  selector:
    app: app: damocles-worker-gpu-{{.UniqueId}}-pod
  ports:
    - protocol: TCP
      port: 17890