// Code generated by go-swagger; DO NOT EDIT.

package plugin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ipfs-force-community/brightbird/models"
)

// AddLabelParamsReader is a Reader for the AddLabelParams structure.
type AddLabelParamsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddLabelParamsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAddLabelParamsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 503:
		result := NewAddLabelParamsServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /plugin/label] addLabelParams", response, response.Code())
	}
}

// NewAddLabelParamsOK creates a AddLabelParamsOK with default headers values
func NewAddLabelParamsOK() *AddLabelParamsOK {
	return &AddLabelParamsOK{}
}

/*
AddLabelParamsOK describes a response with status code 200, with default header values.

AddLabelParamsOK add label params o k
*/
type AddLabelParamsOK struct {
}

// IsSuccess returns true when this add label params o k response has a 2xx status code
func (o *AddLabelParamsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this add label params o k response has a 3xx status code
func (o *AddLabelParamsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this add label params o k response has a 4xx status code
func (o *AddLabelParamsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this add label params o k response has a 5xx status code
func (o *AddLabelParamsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this add label params o k response a status code equal to that given
func (o *AddLabelParamsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the add label params o k response
func (o *AddLabelParamsOK) Code() int {
	return 200
}

func (o *AddLabelParamsOK) Error() string {
	return fmt.Sprintf("[POST /plugin/label][%d] addLabelParamsOK ", 200)
}

func (o *AddLabelParamsOK) String() string {
	return fmt.Sprintf("[POST /plugin/label][%d] addLabelParamsOK ", 200)
}

func (o *AddLabelParamsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddLabelParamsServiceUnavailable creates a AddLabelParamsServiceUnavailable with default headers values
func NewAddLabelParamsServiceUnavailable() *AddLabelParamsServiceUnavailable {
	return &AddLabelParamsServiceUnavailable{}
}

/*
AddLabelParamsServiceUnavailable describes a response with status code 503, with default header values.

apiError
*/
type AddLabelParamsServiceUnavailable struct {
	Payload *models.APIError
}

// IsSuccess returns true when this add label params service unavailable response has a 2xx status code
func (o *AddLabelParamsServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this add label params service unavailable response has a 3xx status code
func (o *AddLabelParamsServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this add label params service unavailable response has a 4xx status code
func (o *AddLabelParamsServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this add label params service unavailable response has a 5xx status code
func (o *AddLabelParamsServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this add label params service unavailable response a status code equal to that given
func (o *AddLabelParamsServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the add label params service unavailable response
func (o *AddLabelParamsServiceUnavailable) Code() int {
	return 503
}

func (o *AddLabelParamsServiceUnavailable) Error() string {
	return fmt.Sprintf("[POST /plugin/label][%d] addLabelParamsServiceUnavailable  %+v", 503, o.Payload)
}

func (o *AddLabelParamsServiceUnavailable) String() string {
	return fmt.Sprintf("[POST /plugin/label][%d] addLabelParamsServiceUnavailable  %+v", 503, o.Payload)
}

func (o *AddLabelParamsServiceUnavailable) GetPayload() *models.APIError {
	return o.Payload
}

func (o *AddLabelParamsServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
