// Code generated by go-swagger; DO NOT EDIT.

package plugin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAddLabelParamsParams creates a new AddLabelParamsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddLabelParamsParams() *AddLabelParamsParams {
	return &AddLabelParamsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddLabelParamsParamsWithTimeout creates a new AddLabelParamsParams object
// with the ability to set a timeout on a request.
func NewAddLabelParamsParamsWithTimeout(timeout time.Duration) *AddLabelParamsParams {
	return &AddLabelParamsParams{
		timeout: timeout,
	}
}

// NewAddLabelParamsParamsWithContext creates a new AddLabelParamsParams object
// with the ability to set a context for a request.
func NewAddLabelParamsParamsWithContext(ctx context.Context) *AddLabelParamsParams {
	return &AddLabelParamsParams{
		Context: ctx,
	}
}

// NewAddLabelParamsParamsWithHTTPClient creates a new AddLabelParamsParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddLabelParamsParamsWithHTTPClient(client *http.Client) *AddLabelParamsParams {
	return &AddLabelParamsParams{
		HTTPClient: client,
	}
}

/*
AddLabelParamsParams contains all the parameters to send to the API endpoint

	for the add label params operation.

	Typically these are written to a http.Request.
*/
type AddLabelParamsParams struct {

	/* Label.

	   plugin type
	*/
	Label *string

	/* Name.

	   name of plugin
	*/
	Name *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add label params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddLabelParamsParams) WithDefaults() *AddLabelParamsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add label params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddLabelParamsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add label params params
func (o *AddLabelParamsParams) WithTimeout(timeout time.Duration) *AddLabelParamsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add label params params
func (o *AddLabelParamsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add label params params
func (o *AddLabelParamsParams) WithContext(ctx context.Context) *AddLabelParamsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add label params params
func (o *AddLabelParamsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add label params params
func (o *AddLabelParamsParams) WithHTTPClient(client *http.Client) *AddLabelParamsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add label params params
func (o *AddLabelParamsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLabel adds the label to the add label params params
func (o *AddLabelParamsParams) WithLabel(label *string) *AddLabelParamsParams {
	o.SetLabel(label)
	return o
}

// SetLabel adds the label to the add label params params
func (o *AddLabelParamsParams) SetLabel(label *string) {
	o.Label = label
}

// WithName adds the name to the add label params params
func (o *AddLabelParamsParams) WithName(name *string) *AddLabelParamsParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the add label params params
func (o *AddLabelParamsParams) SetName(name *string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *AddLabelParamsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Label != nil {

		// query param label
		var qrLabel string

		if o.Label != nil {
			qrLabel = *o.Label
		}
		qLabel := qrLabel
		if qLabel != "" {

			if err := r.SetQueryParam("label", qLabel); err != nil {
				return err
			}
		}
	}

	if o.Name != nil {

		// query param name
		var qrName string

		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {

			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
