// Code generated by go-swagger; DO NOT EDIT.

package plugin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hunjixin/brightbird/models"
)

// DeleteLabelParamsReader is a Reader for the DeleteLabelParams structure.
type DeleteLabelParamsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteLabelParamsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteLabelParamsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 503:
		result := NewDeleteLabelParamsServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteLabelParamsOK creates a DeleteLabelParamsOK with default headers values
func NewDeleteLabelParamsOK() *DeleteLabelParamsOK {
	return &DeleteLabelParamsOK{}
}

/*
DeleteLabelParamsOK describes a response with status code 200, with default header values.

DeleteLabelParamsOK delete label params o k
*/
type DeleteLabelParamsOK struct {
}

// IsSuccess returns true when this delete label params o k response has a 2xx status code
func (o *DeleteLabelParamsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete label params o k response has a 3xx status code
func (o *DeleteLabelParamsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete label params o k response has a 4xx status code
func (o *DeleteLabelParamsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete label params o k response has a 5xx status code
func (o *DeleteLabelParamsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete label params o k response a status code equal to that given
func (o *DeleteLabelParamsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete label params o k response
func (o *DeleteLabelParamsOK) Code() int {
	return 200
}

func (o *DeleteLabelParamsOK) Error() string {
	return fmt.Sprintf("[DELETE /plugin/label][%d] deleteLabelParamsOK ", 200)
}

func (o *DeleteLabelParamsOK) String() string {
	return fmt.Sprintf("[DELETE /plugin/label][%d] deleteLabelParamsOK ", 200)
}

func (o *DeleteLabelParamsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteLabelParamsServiceUnavailable creates a DeleteLabelParamsServiceUnavailable with default headers values
func NewDeleteLabelParamsServiceUnavailable() *DeleteLabelParamsServiceUnavailable {
	return &DeleteLabelParamsServiceUnavailable{}
}

/*
DeleteLabelParamsServiceUnavailable describes a response with status code 503, with default header values.

apiError
*/
type DeleteLabelParamsServiceUnavailable struct {
	Payload *models.APIError
}

// IsSuccess returns true when this delete label params service unavailable response has a 2xx status code
func (o *DeleteLabelParamsServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete label params service unavailable response has a 3xx status code
func (o *DeleteLabelParamsServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete label params service unavailable response has a 4xx status code
func (o *DeleteLabelParamsServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete label params service unavailable response has a 5xx status code
func (o *DeleteLabelParamsServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this delete label params service unavailable response a status code equal to that given
func (o *DeleteLabelParamsServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the delete label params service unavailable response
func (o *DeleteLabelParamsServiceUnavailable) Code() int {
	return 503
}

func (o *DeleteLabelParamsServiceUnavailable) Error() string {
	return fmt.Sprintf("[DELETE /plugin/label][%d] deleteLabelParamsServiceUnavailable  %+v", 503, o.Payload)
}

func (o *DeleteLabelParamsServiceUnavailable) String() string {
	return fmt.Sprintf("[DELETE /plugin/label][%d] deleteLabelParamsServiceUnavailable  %+v", 503, o.Payload)
}

func (o *DeleteLabelParamsServiceUnavailable) GetPayload() *models.APIError {
	return o.Payload
}

func (o *DeleteLabelParamsServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
