// Code generated by go-swagger; DO NOT EDIT.

package plugin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ipfs-force-community/brightbird/models"
)

// DeletePluginByVersionReqReader is a Reader for the DeletePluginByVersionReq structure.
type DeletePluginByVersionReqReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeletePluginByVersionReqReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeletePluginByVersionReqOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 503:
		result := NewDeletePluginByVersionReqServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /plugin] deletePluginByVersionReq", response, response.Code())
	}
}

// NewDeletePluginByVersionReqOK creates a DeletePluginByVersionReqOK with default headers values
func NewDeletePluginByVersionReqOK() *DeletePluginByVersionReqOK {
	return &DeletePluginByVersionReqOK{}
}

/*
DeletePluginByVersionReqOK describes a response with status code 200, with default header values.

DeletePluginByVersionReqOK delete plugin by version req o k
*/
type DeletePluginByVersionReqOK struct {
}

// IsSuccess returns true when this delete plugin by version req o k response has a 2xx status code
func (o *DeletePluginByVersionReqOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete plugin by version req o k response has a 3xx status code
func (o *DeletePluginByVersionReqOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete plugin by version req o k response has a 4xx status code
func (o *DeletePluginByVersionReqOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete plugin by version req o k response has a 5xx status code
func (o *DeletePluginByVersionReqOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete plugin by version req o k response a status code equal to that given
func (o *DeletePluginByVersionReqOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete plugin by version req o k response
func (o *DeletePluginByVersionReqOK) Code() int {
	return 200
}

func (o *DeletePluginByVersionReqOK) Error() string {
	return fmt.Sprintf("[DELETE /plugin][%d] deletePluginByVersionReqOK ", 200)
}

func (o *DeletePluginByVersionReqOK) String() string {
	return fmt.Sprintf("[DELETE /plugin][%d] deletePluginByVersionReqOK ", 200)
}

func (o *DeletePluginByVersionReqOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeletePluginByVersionReqServiceUnavailable creates a DeletePluginByVersionReqServiceUnavailable with default headers values
func NewDeletePluginByVersionReqServiceUnavailable() *DeletePluginByVersionReqServiceUnavailable {
	return &DeletePluginByVersionReqServiceUnavailable{}
}

/*
DeletePluginByVersionReqServiceUnavailable describes a response with status code 503, with default header values.

apiError
*/
type DeletePluginByVersionReqServiceUnavailable struct {
	Payload *models.APIError
}

// IsSuccess returns true when this delete plugin by version req service unavailable response has a 2xx status code
func (o *DeletePluginByVersionReqServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete plugin by version req service unavailable response has a 3xx status code
func (o *DeletePluginByVersionReqServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete plugin by version req service unavailable response has a 4xx status code
func (o *DeletePluginByVersionReqServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete plugin by version req service unavailable response has a 5xx status code
func (o *DeletePluginByVersionReqServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this delete plugin by version req service unavailable response a status code equal to that given
func (o *DeletePluginByVersionReqServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the delete plugin by version req service unavailable response
func (o *DeletePluginByVersionReqServiceUnavailable) Code() int {
	return 503
}

func (o *DeletePluginByVersionReqServiceUnavailable) Error() string {
	return fmt.Sprintf("[DELETE /plugin][%d] deletePluginByVersionReqServiceUnavailable  %+v", 503, o.Payload)
}

func (o *DeletePluginByVersionReqServiceUnavailable) String() string {
	return fmt.Sprintf("[DELETE /plugin][%d] deletePluginByVersionReqServiceUnavailable  %+v", 503, o.Payload)
}

func (o *DeletePluginByVersionReqServiceUnavailable) GetPayload() *models.APIError {
	return o.Payload
}

func (o *DeletePluginByVersionReqServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
