// Code generated by go-swagger; DO NOT EDIT.

package plugin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ipfs-force-community/brightbird/models"
)

// DeletePluginReqReader is a Reader for the DeletePluginReq structure.
type DeletePluginReqReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeletePluginReqReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeletePluginReqOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 503:
		result := NewDeletePluginReqServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /plugin/all] deletePluginReq", response, response.Code())
	}
}

// NewDeletePluginReqOK creates a DeletePluginReqOK with default headers values
func NewDeletePluginReqOK() *DeletePluginReqOK {
	return &DeletePluginReqOK{}
}

/*
DeletePluginReqOK describes a response with status code 200, with default header values.

DeletePluginReqOK delete plugin req o k
*/
type DeletePluginReqOK struct {
}

// IsSuccess returns true when this delete plugin req o k response has a 2xx status code
func (o *DeletePluginReqOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete plugin req o k response has a 3xx status code
func (o *DeletePluginReqOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete plugin req o k response has a 4xx status code
func (o *DeletePluginReqOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete plugin req o k response has a 5xx status code
func (o *DeletePluginReqOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete plugin req o k response a status code equal to that given
func (o *DeletePluginReqOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete plugin req o k response
func (o *DeletePluginReqOK) Code() int {
	return 200
}

func (o *DeletePluginReqOK) Error() string {
	return fmt.Sprintf("[DELETE /plugin/all][%d] deletePluginReqOK ", 200)
}

func (o *DeletePluginReqOK) String() string {
	return fmt.Sprintf("[DELETE /plugin/all][%d] deletePluginReqOK ", 200)
}

func (o *DeletePluginReqOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeletePluginReqServiceUnavailable creates a DeletePluginReqServiceUnavailable with default headers values
func NewDeletePluginReqServiceUnavailable() *DeletePluginReqServiceUnavailable {
	return &DeletePluginReqServiceUnavailable{}
}

/*
DeletePluginReqServiceUnavailable describes a response with status code 503, with default header values.

apiError
*/
type DeletePluginReqServiceUnavailable struct {
	Payload *models.APIError
}

// IsSuccess returns true when this delete plugin req service unavailable response has a 2xx status code
func (o *DeletePluginReqServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete plugin req service unavailable response has a 3xx status code
func (o *DeletePluginReqServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete plugin req service unavailable response has a 4xx status code
func (o *DeletePluginReqServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete plugin req service unavailable response has a 5xx status code
func (o *DeletePluginReqServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this delete plugin req service unavailable response a status code equal to that given
func (o *DeletePluginReqServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the delete plugin req service unavailable response
func (o *DeletePluginReqServiceUnavailable) Code() int {
	return 503
}

func (o *DeletePluginReqServiceUnavailable) Error() string {
	return fmt.Sprintf("[DELETE /plugin/all][%d] deletePluginReqServiceUnavailable  %+v", 503, o.Payload)
}

func (o *DeletePluginReqServiceUnavailable) String() string {
	return fmt.Sprintf("[DELETE /plugin/all][%d] deletePluginReqServiceUnavailable  %+v", 503, o.Payload)
}

func (o *DeletePluginReqServiceUnavailable) GetPayload() *models.APIError {
	return o.Payload
}

func (o *DeletePluginReqServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
