// Code generated by go-swagger; DO NOT EDIT.

package plugin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPluginDefParams creates a new GetPluginDefParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPluginDefParams() *GetPluginDefParams {
	return &GetPluginDefParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPluginDefParamsWithTimeout creates a new GetPluginDefParams object
// with the ability to set a timeout on a request.
func NewGetPluginDefParamsWithTimeout(timeout time.Duration) *GetPluginDefParams {
	return &GetPluginDefParams{
		timeout: timeout,
	}
}

// NewGetPluginDefParamsWithContext creates a new GetPluginDefParams object
// with the ability to set a context for a request.
func NewGetPluginDefParamsWithContext(ctx context.Context) *GetPluginDefParams {
	return &GetPluginDefParams{
		Context: ctx,
	}
}

// NewGetPluginDefParamsWithHTTPClient creates a new GetPluginDefParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPluginDefParamsWithHTTPClient(client *http.Client) *GetPluginDefParams {
	return &GetPluginDefParams{
		HTTPClient: client,
	}
}

/*
GetPluginDefParams contains all the parameters to send to the API endpoint

	for the get plugin def operation.

	Typically these are written to a http.Request.
*/
type GetPluginDefParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get plugin def params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPluginDefParams) WithDefaults() *GetPluginDefParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get plugin def params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPluginDefParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get plugin def params
func (o *GetPluginDefParams) WithTimeout(timeout time.Duration) *GetPluginDefParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get plugin def params
func (o *GetPluginDefParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get plugin def params
func (o *GetPluginDefParams) WithContext(ctx context.Context) *GetPluginDefParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get plugin def params
func (o *GetPluginDefParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get plugin def params
func (o *GetPluginDefParams) WithHTTPClient(client *http.Client) *GetPluginDefParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get plugin def params
func (o *GetPluginDefParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetPluginDefParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
