// Code generated by go-swagger; DO NOT EDIT.

package plugin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/hunjixin/brightbird/models"
)

// ListMainFestParamsReader is a Reader for the ListMainFestParams structure.
type ListMainFestParamsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListMainFestParamsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListMainFestParamsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 503:
		result := NewListMainFestParamsServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListMainFestParamsOK creates a ListMainFestParamsOK with default headers values
func NewListMainFestParamsOK() *ListMainFestParamsOK {
	return &ListMainFestParamsOK{}
}

/*
ListMainFestParamsOK describes a response with status code 200, with default header values.

pluginInfo
*/
type ListMainFestParamsOK struct {
	Payload []*models.PluginInfo
}

// IsSuccess returns true when this list main fest params o k response has a 2xx status code
func (o *ListMainFestParamsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list main fest params o k response has a 3xx status code
func (o *ListMainFestParamsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list main fest params o k response has a 4xx status code
func (o *ListMainFestParamsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list main fest params o k response has a 5xx status code
func (o *ListMainFestParamsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list main fest params o k response a status code equal to that given
func (o *ListMainFestParamsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list main fest params o k response
func (o *ListMainFestParamsOK) Code() int {
	return 200
}

func (o *ListMainFestParamsOK) Error() string {
	return fmt.Sprintf("[GET /plugin/mainfest][%d] listMainFestParamsOK  %+v", 200, o.Payload)
}

func (o *ListMainFestParamsOK) String() string {
	return fmt.Sprintf("[GET /plugin/mainfest][%d] listMainFestParamsOK  %+v", 200, o.Payload)
}

func (o *ListMainFestParamsOK) GetPayload() []*models.PluginInfo {
	return o.Payload
}

func (o *ListMainFestParamsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListMainFestParamsServiceUnavailable creates a ListMainFestParamsServiceUnavailable with default headers values
func NewListMainFestParamsServiceUnavailable() *ListMainFestParamsServiceUnavailable {
	return &ListMainFestParamsServiceUnavailable{}
}

/*
ListMainFestParamsServiceUnavailable describes a response with status code 503, with default header values.

apiError
*/
type ListMainFestParamsServiceUnavailable struct {
	Payload *models.APIError
}

// IsSuccess returns true when this list main fest params service unavailable response has a 2xx status code
func (o *ListMainFestParamsServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list main fest params service unavailable response has a 3xx status code
func (o *ListMainFestParamsServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list main fest params service unavailable response has a 4xx status code
func (o *ListMainFestParamsServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this list main fest params service unavailable response has a 5xx status code
func (o *ListMainFestParamsServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this list main fest params service unavailable response a status code equal to that given
func (o *ListMainFestParamsServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the list main fest params service unavailable response
func (o *ListMainFestParamsServiceUnavailable) Code() int {
	return 503
}

func (o *ListMainFestParamsServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /plugin/mainfest][%d] listMainFestParamsServiceUnavailable  %+v", 503, o.Payload)
}

func (o *ListMainFestParamsServiceUnavailable) String() string {
	return fmt.Sprintf("[GET /plugin/mainfest][%d] listMainFestParamsServiceUnavailable  %+v", 503, o.Payload)
}

func (o *ListMainFestParamsServiceUnavailable) GetPayload() *models.APIError {
	return o.Payload
}

func (o *ListMainFestParamsServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
