// Code generated by go-swagger; DO NOT EDIT.

package plugin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ipfs-force-community/brightbird/models"
)

// UploadPluginFilesParamsReader is a Reader for the UploadPluginFilesParams structure.
type UploadPluginFilesParamsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UploadPluginFilesParamsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUploadPluginFilesParamsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 503:
		result := NewUploadPluginFilesParamsServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /plugin/upload] uploadPluginFilesParams", response, response.Code())
	}
}

// NewUploadPluginFilesParamsOK creates a UploadPluginFilesParamsOK with default headers values
func NewUploadPluginFilesParamsOK() *UploadPluginFilesParamsOK {
	return &UploadPluginFilesParamsOK{}
}

/*
UploadPluginFilesParamsOK describes a response with status code 200, with default header values.

UploadPluginFilesParamsOK upload plugin files params o k
*/
type UploadPluginFilesParamsOK struct {
}

// IsSuccess returns true when this upload plugin files params o k response has a 2xx status code
func (o *UploadPluginFilesParamsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this upload plugin files params o k response has a 3xx status code
func (o *UploadPluginFilesParamsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this upload plugin files params o k response has a 4xx status code
func (o *UploadPluginFilesParamsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this upload plugin files params o k response has a 5xx status code
func (o *UploadPluginFilesParamsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this upload plugin files params o k response a status code equal to that given
func (o *UploadPluginFilesParamsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the upload plugin files params o k response
func (o *UploadPluginFilesParamsOK) Code() int {
	return 200
}

func (o *UploadPluginFilesParamsOK) Error() string {
	return fmt.Sprintf("[POST /plugin/upload][%d] uploadPluginFilesParamsOK ", 200)
}

func (o *UploadPluginFilesParamsOK) String() string {
	return fmt.Sprintf("[POST /plugin/upload][%d] uploadPluginFilesParamsOK ", 200)
}

func (o *UploadPluginFilesParamsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUploadPluginFilesParamsServiceUnavailable creates a UploadPluginFilesParamsServiceUnavailable with default headers values
func NewUploadPluginFilesParamsServiceUnavailable() *UploadPluginFilesParamsServiceUnavailable {
	return &UploadPluginFilesParamsServiceUnavailable{}
}

/*
UploadPluginFilesParamsServiceUnavailable describes a response with status code 503, with default header values.

apiError
*/
type UploadPluginFilesParamsServiceUnavailable struct {
	Payload *models.APIError
}

// IsSuccess returns true when this upload plugin files params service unavailable response has a 2xx status code
func (o *UploadPluginFilesParamsServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this upload plugin files params service unavailable response has a 3xx status code
func (o *UploadPluginFilesParamsServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this upload plugin files params service unavailable response has a 4xx status code
func (o *UploadPluginFilesParamsServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this upload plugin files params service unavailable response has a 5xx status code
func (o *UploadPluginFilesParamsServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this upload plugin files params service unavailable response a status code equal to that given
func (o *UploadPluginFilesParamsServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the upload plugin files params service unavailable response
func (o *UploadPluginFilesParamsServiceUnavailable) Code() int {
	return 503
}

func (o *UploadPluginFilesParamsServiceUnavailable) Error() string {
	return fmt.Sprintf("[POST /plugin/upload][%d] uploadPluginFilesParamsServiceUnavailable  %+v", 503, o.Payload)
}

func (o *UploadPluginFilesParamsServiceUnavailable) String() string {
	return fmt.Sprintf("[POST /plugin/upload][%d] uploadPluginFilesParamsServiceUnavailable  %+v", 503, o.Payload)
}

func (o *UploadPluginFilesParamsServiceUnavailable) GetPayload() *models.APIError {
	return o.Payload
}

func (o *UploadPluginFilesParamsServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
