// Code generated by go-swagger; DO NOT EDIT.

package list

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewLabelParams creates a new LabelParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewLabelParams() *LabelParams {
	return &LabelParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewLabelParamsWithTimeout creates a new LabelParams object
// with the ability to set a timeout on a request.
func NewLabelParamsWithTimeout(timeout time.Duration) *LabelParams {
	return &LabelParams{
		timeout: timeout,
	}
}

// NewLabelParamsWithContext creates a new LabelParams object
// with the ability to set a context for a request.
func NewLabelParamsWithContext(ctx context.Context) *LabelParams {
	return &LabelParams{
		Context: ctx,
	}
}

// NewLabelParamsWithHTTPClient creates a new LabelParams object
// with the ability to set a custom HTTPClient for a request.
func NewLabelParamsWithHTTPClient(client *http.Client) *LabelParams {
	return &LabelParams{
		HTTPClient: client,
	}
}

/*
LabelParams contains all the parameters to send to the API endpoint

	for the label operation.

	Typically these are written to a http.Request.
*/
type LabelParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the label params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LabelParams) WithDefaults() *LabelParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the label params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LabelParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the label params
func (o *LabelParams) WithTimeout(timeout time.Duration) *LabelParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the label params
func (o *LabelParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the label params
func (o *LabelParams) WithContext(ctx context.Context) *LabelParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the label params
func (o *LabelParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the label params
func (o *LabelParams) WithHTTPClient(client *http.Client) *LabelParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the label params
func (o *LabelParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *LabelParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
