apiVersion: v1
kind: Service
metadata:
  name: sophon-miner-{{.UniqueId}}-svc
spec:
  clusterIP: None
  selector:
    app: sophon-miner-{{.UniqueId}}-pod
  ports:
    - protocol: TCP
      port: 12308
      name: api

