apiVersion: v1
kind: Service
metadata:
  name: sophon-auth-{{.UniqueId}}-service
spec:
  clusterIP: None
  selector:
    app: sophon-auth-{{.UniqueId}}-pod
  ports:
    - protocol: TCP
      port: 8989