apiVersion: v1
kind: Service
metadata:
  name: venus-wallet-pro-{{.UniqueId}}-svc
spec:
  clusterIP: None
  selector:
    app: venus-wallet-pro-{{.UniqueId}}-pod
  ports:
    - protocol: TCP
      port: 5679
      name: api

