apiVersion: v1
kind: Service
metadata:
  name: venus-wallet-{{.UniqueId}}-svc
spec:
  clusterIP: None
  selector:
    app: venus-wallet-{{.UniqueId}}-pod
  ports:
    - protocol: TCP
      port: 5678
      name: api

