// Code generated by go-swagger; DO NOT EDIT.

package test_data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ipfs-force-community/brightbird/models"
)

// ListTestDataReader is a Reader for the ListTestData structure.
type ListTestDataReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListTestDataReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListTestDataOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewListTestDataInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /test-data] listTestData", response, response.Code())
	}
}

// NewListTestDataOK creates a ListTestDataOK with default headers values
func NewListTestDataOK() *ListTestDataOK {
	return &ListTestDataOK{}
}

/*
ListTestDataOK describes a response with status code 200, with default header values.

	//todo fix correctstruct
*/
type ListTestDataOK struct {
	Payload models.MyString
}

// IsSuccess returns true when this list test data o k response has a 2xx status code
func (o *ListTestDataOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list test data o k response has a 3xx status code
func (o *ListTestDataOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list test data o k response has a 4xx status code
func (o *ListTestDataOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list test data o k response has a 5xx status code
func (o *ListTestDataOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list test data o k response a status code equal to that given
func (o *ListTestDataOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list test data o k response
func (o *ListTestDataOK) Code() int {
	return 200
}

func (o *ListTestDataOK) Error() string {
	return fmt.Sprintf("[GET /test-data][%d] listTestDataOK  %+v", 200, o.Payload)
}

func (o *ListTestDataOK) String() string {
	return fmt.Sprintf("[GET /test-data][%d] listTestDataOK  %+v", 200, o.Payload)
}

func (o *ListTestDataOK) GetPayload() models.MyString {
	return o.Payload
}

func (o *ListTestDataOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListTestDataInternalServerError creates a ListTestDataInternalServerError with default headers values
func NewListTestDataInternalServerError() *ListTestDataInternalServerError {
	return &ListTestDataInternalServerError{}
}

/*
ListTestDataInternalServerError describes a response with status code 500, with default header values.

apiError
*/
type ListTestDataInternalServerError struct {
	Payload *models.APIError
}

// IsSuccess returns true when this list test data internal server error response has a 2xx status code
func (o *ListTestDataInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list test data internal server error response has a 3xx status code
func (o *ListTestDataInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list test data internal server error response has a 4xx status code
func (o *ListTestDataInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this list test data internal server error response has a 5xx status code
func (o *ListTestDataInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this list test data internal server error response a status code equal to that given
func (o *ListTestDataInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the list test data internal server error response
func (o *ListTestDataInternalServerError) Code() int {
	return 500
}

func (o *ListTestDataInternalServerError) Error() string {
	return fmt.Sprintf("[GET /test-data][%d] listTestDataInternalServerError  %+v", 500, o.Payload)
}

func (o *ListTestDataInternalServerError) String() string {
	return fmt.Sprintf("[GET /test-data][%d] listTestDataInternalServerError  %+v", 500, o.Payload)
}

func (o *ListTestDataInternalServerError) GetPayload() *models.APIError {
	return o.Payload
}

func (o *ListTestDataInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
