// Code generated by go-swagger; DO NOT EDIT.

package success_quantity_trends

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSuccessQuantityTrendsReqParams creates a new SuccessQuantityTrendsReqParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSuccessQuantityTrendsReqParams() *SuccessQuantityTrendsReqParams {
	return &SuccessQuantityTrendsReqParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSuccessQuantityTrendsReqParamsWithTimeout creates a new SuccessQuantityTrendsReqParams object
// with the ability to set a timeout on a request.
func NewSuccessQuantityTrendsReqParamsWithTimeout(timeout time.Duration) *SuccessQuantityTrendsReqParams {
	return &SuccessQuantityTrendsReqParams{
		timeout: timeout,
	}
}

// NewSuccessQuantityTrendsReqParamsWithContext creates a new SuccessQuantityTrendsReqParams object
// with the ability to set a context for a request.
func NewSuccessQuantityTrendsReqParamsWithContext(ctx context.Context) *SuccessQuantityTrendsReqParams {
	return &SuccessQuantityTrendsReqParams{
		Context: ctx,
	}
}

// NewSuccessQuantityTrendsReqParamsWithHTTPClient creates a new SuccessQuantityTrendsReqParams object
// with the ability to set a custom HTTPClient for a request.
func NewSuccessQuantityTrendsReqParamsWithHTTPClient(client *http.Client) *SuccessQuantityTrendsReqParams {
	return &SuccessQuantityTrendsReqParams{
		HTTPClient: client,
	}
}

/*
SuccessQuantityTrendsReqParams contains all the parameters to send to the API endpoint

	for the success quantity trends req operation.

	Typically these are written to a http.Request.
*/
type SuccessQuantityTrendsReqParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the success quantity trends req params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SuccessQuantityTrendsReqParams) WithDefaults() *SuccessQuantityTrendsReqParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the success quantity trends req params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SuccessQuantityTrendsReqParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the success quantity trends req params
func (o *SuccessQuantityTrendsReqParams) WithTimeout(timeout time.Duration) *SuccessQuantityTrendsReqParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the success quantity trends req params
func (o *SuccessQuantityTrendsReqParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the success quantity trends req params
func (o *SuccessQuantityTrendsReqParams) WithContext(ctx context.Context) *SuccessQuantityTrendsReqParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the success quantity trends req params
func (o *SuccessQuantityTrendsReqParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the success quantity trends req params
func (o *SuccessQuantityTrendsReqParams) WithHTTPClient(client *http.Client) *SuccessQuantityTrendsReqParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the success quantity trends req params
func (o *SuccessQuantityTrendsReqParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *SuccessQuantityTrendsReqParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
