// Code generated by go-swagger; DO NOT EDIT.

package log

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ipfs-force-community/brightbird/models"
)

// ListPodsReqReader is a Reader for the ListPodsReq structure.
type ListPodsReqReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListPodsReqReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListPodsReqOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 503:
		result := NewListPodsReqServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /logs/pods] listPodsReq", response, response.Code())
	}
}

// NewListPodsReqOK creates a ListPodsReqOK with default headers values
func NewListPodsReqOK() *ListPodsReqOK {
	return &ListPodsReqOK{}
}

/*
ListPodsReqOK describes a response with status code 200, with default header values.

stringArr
*/
type ListPodsReqOK struct {
	Payload models.StringArray
}

// IsSuccess returns true when this list pods req o k response has a 2xx status code
func (o *ListPodsReqOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list pods req o k response has a 3xx status code
func (o *ListPodsReqOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list pods req o k response has a 4xx status code
func (o *ListPodsReqOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list pods req o k response has a 5xx status code
func (o *ListPodsReqOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list pods req o k response a status code equal to that given
func (o *ListPodsReqOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list pods req o k response
func (o *ListPodsReqOK) Code() int {
	return 200
}

func (o *ListPodsReqOK) Error() string {
	return fmt.Sprintf("[GET /logs/pods][%d] listPodsReqOK  %+v", 200, o.Payload)
}

func (o *ListPodsReqOK) String() string {
	return fmt.Sprintf("[GET /logs/pods][%d] listPodsReqOK  %+v", 200, o.Payload)
}

func (o *ListPodsReqOK) GetPayload() models.StringArray {
	return o.Payload
}

func (o *ListPodsReqOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListPodsReqServiceUnavailable creates a ListPodsReqServiceUnavailable with default headers values
func NewListPodsReqServiceUnavailable() *ListPodsReqServiceUnavailable {
	return &ListPodsReqServiceUnavailable{}
}

/*
ListPodsReqServiceUnavailable describes a response with status code 503, with default header values.

apiError
*/
type ListPodsReqServiceUnavailable struct {
	Payload *models.APIError
}

// IsSuccess returns true when this list pods req service unavailable response has a 2xx status code
func (o *ListPodsReqServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list pods req service unavailable response has a 3xx status code
func (o *ListPodsReqServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list pods req service unavailable response has a 4xx status code
func (o *ListPodsReqServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this list pods req service unavailable response has a 5xx status code
func (o *ListPodsReqServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this list pods req service unavailable response a status code equal to that given
func (o *ListPodsReqServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the list pods req service unavailable response
func (o *ListPodsReqServiceUnavailable) Code() int {
	return 503
}

func (o *ListPodsReqServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /logs/pods][%d] listPodsReqServiceUnavailable  %+v", 503, o.Payload)
}

func (o *ListPodsReqServiceUnavailable) String() string {
	return fmt.Sprintf("[GET /logs/pods][%d] listPodsReqServiceUnavailable  %+v", 503, o.Payload)
}

func (o *ListPodsReqServiceUnavailable) GetPayload() *models.APIError {
	return o.Payload
}

func (o *ListPodsReqServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
