// Code generated by go-swagger; DO NOT EDIT.

package log

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new log API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for log API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	ListLogsInPod(params *ListLogsInPodParams, opts ...ClientOption) (*ListLogsInPodOK, error)

	ListPodsInTest(params *ListPodsInTestParams, opts ...ClientOption) (*ListPodsInTestOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
ListLogsInPod gets all logs in pod
*/
func (a *Client) ListLogsInPod(params *ListLogsInPodParams, opts ...ClientOption) (*ListLogsInPodOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListLogsInPodParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "listLogsInPod",
		Method:             "GET",
		PathPattern:        "/logs/{podName}",
		ProducesMediaTypes: []string{"application/json", "application/text"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ListLogsInPodReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListLogsInPodOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for listLogsInPod: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
ListPodsInTest lists all pod names in test
*/
func (a *Client) ListPodsInTest(params *ListPodsInTestParams, opts ...ClientOption) (*ListPodsInTestOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListPodsInTestParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "listPodsInTest",
		Method:             "GET",
		PathPattern:        "/logs/pods/{testid}",
		ProducesMediaTypes: []string{"application/json", "application/text"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ListPodsInTestReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListPodsInTestOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for listPodsInTest: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
