// Code generated by go-swagger; DO NOT EDIT.

package log

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new log API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for log API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	ListPodsReq(params *ListPodsReqParams, opts ...ClientOption) (*ListPodsReqOK, error)

	PodLogReq(params *PodLogReqParams, opts ...ClientOption) (*PodLogReqOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
ListPodsReq lists all pod names in test
*/
func (a *Client) ListPodsReq(params *ListPodsReqParams, opts ...ClientOption) (*ListPodsReqOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListPodsReqParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "listPodsReq",
		Method:             "GET",
		PathPattern:        "/logs/pods",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json", "application/xml"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ListPodsReqReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListPodsReqOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for listPodsReq: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PodLogReq gets all logs in pod
*/
func (a *Client) PodLogReq(params *PodLogReqParams, opts ...ClientOption) (*PodLogReqOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPodLogReqParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "podLogReq",
		Method:             "GET",
		PathPattern:        "/logs",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json", "application/xml"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &PodLogReqReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PodLogReqOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for podLogReq: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
