name: docker-image

on:
  pull_request:
    branches:
      - '**'
  push:
    tags:
      - '*'
  workflow_call:
    secrets:
      DOCKER_PASSWORD:
        required: true
      DOCKER_USERNAME:
        required: true
  
jobs:

  build_docker_image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Create vars
        id: vars
        run: |
          export github_tag=${{ github.ref_name }}
          export is_tag_create=false

          export rx_tag='^refs\/tags\/.*'
          export rx_version_tag='^v([0-9]+\.){0,2}(\*|[0-9]+)(-rc[0-9]*){0,1}$'
          if [[ "${{github.ref}}" =~ $rx_tag ]]; then
            export is_tag_create=true
          fi

          echo "::set-output name=github_tag::$github_tag"
          echo "::set-output name=is_tag_create::$is_tag_create"

      - name: Show environment
        run: |
          echo is_tag_create = ${{ steps.vars.outputs.is_tag_create }}
          echo github_tag = ${{ steps.vars.outputs.github_tag }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        if: ${{ steps.vars.outputs.is_tag_create == 'true' }}
        run: |
          make docker-backend TAG=latest
          make docker-backend TAG=${{ steps.vars.outputs.github_tag }}
          make docker-front TAG=latest
          make docker-front TAG=${{ steps.vars.outputs.github_tag }}
          make docker-plugin TAG=latest
          make docker-plugin TAG=${{ steps.vars.outputs.github_tag }}
          make docker-runner TAG=latest
          make docker-runner TAG=${{ steps.vars.outputs.github_tag }}
      
