name: go-check

on:
  pull_request:
    branches:
      - '**'
      
jobs:

  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true

      - name: install default deps
        run: sudo apt-get -o Acquire::Retries=3 update && sudo apt-get -o Acquire::Retries=3 install make ftp git bzr curl wget -y

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org,direct"
          GO111MODULE: "on"
        run: |
          make build-go

      - name: go-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.51.1
          golangci-lint run --timeout 10m

      - name: Detect changes
        run: |
          go mod tidy
          git status --porcelain
          test -z "$(git status --porcelain)"

      - name: Run coverage
        run:  go test -coverpkg=./... -race -coverprofile=coverage.txt -covermode=atomic ./... -v --timeout 20m

      - name: Upload
        uses: codecov/codecov-action@v3
        with:
          # https://github.com/codecov/codecov-action/issues/557#issuecomment-1216749652
          token: ${{ secrets.CODECOV_TOKEN }}
          files:  ./coverage.txt
          flags: unittests
          name: brightbird
          fail_ci_if_error: true
          verbose: true