name: go-check

on:
  pull_request:
    branches:
      - '**'
      
jobs:

  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.3
          cache: true

      - name: install default deps
        run: sudo apt-get -o Acquire::Retries=3 update && sudo apt-get -o Acquire::Retries=3 install make ftp git bzr curl wget -y


  # todo ci not work exactly like local machine
  #- name: gen
  #  run: |
  #    download_url=$(curl -s https://api.github.com/repos/go-swagger/go-swagger/releases/latest | \
  #    jq -r '.assets[] | select(.name | contains("'"$(uname | tr '[:upper:]' '[:lower:]')"'_amd64")) | .browser_download_url')
  #    curl -o /usr/local/bin/swagger -L'#' "$download_url"
  ##    chmod +x /usr/local/bin/swagger
  #    make gen-swagger

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org,direct"
          GO111MODULE: "on"
        run: |
          make build-go

      - name: go-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.51.1
          golangci-lint run --timeout 10m

      - name: Detect changes
        run: |
          go mod tidy
          git status --porcelain
          test -z "$(git status --porcelain)"

      - name: Test
        run:  go test -race -v --timeout 20m  `go list ./... | grep -v ui`
